### ISSUE TITLE
/my/topics/:topicId - Invite Users UX annoyances

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#100]
**Reproduce**

* Go to `/my/topics/:topicId`
* Press "invite" in the "Users list"
* Search a user and click "Save topic and send invite"

**Result**

* "Users list" section is closed
* "Users list (COUNT)" - COUNT is not updated
* "General information" "Users" - count is not updated 
* Once "Users list" is re-opened, counts update, BUT page scrolls to "Users list" section (which is expected only if the section is out of viewport).

**TODO**

- [x] Do not close "Users list" section.
- [x] Update User list in the "Users list" section AND the counts in the header and "General information" section.
- [x] Scroll to "User list" section ONLY if it's out of the viewport.

![image](https://user-images.githubusercontent.com/7405383/47801145-39a6b800-dd36-11e8-9cf7-f329b34128c7.png)

**Comment by tiblu** [comment]
https://github.com/citizenos/citizenos-fe/commit/c4dc8b3e7da0f5e89e4172b28f189022b36da62c

**Comment by tiblu** [comment]
Reopening this bug as the implementation is not crisp. 

We should make a new implementation that:

* Loads the extra (user list, group list etc) based on `openTabs` url parameters
* Tab visibility depends on if a url parameter is present or not

Open questions:

* Should we assume a person wants to keeps same tabs open when navigating to another tab/group?

**Comment by loorm** [comment]
Triage 15: 3 days. And keeping the same tab open across topics is fine.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
