### ISSUE TITLE
SECURITY: Content Security Policy (CSP) - https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#101]
**Overview**

In order to add extra level of protection against XSS and packet sniffing attacks we should implement Content Security Policy (CSP) - https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

**TODO**

- [x] Investigate proper implementation for CSP, implement it using `<meta>` tags OR headers, which ever makes sense (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy). I think for us headers make more sense and are easier to implement.
- [x] Implement and enable reporting of violations - https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP#Enabling_reporting
- [x] Release with report-only
- [x] Remove report-only when test period issues are fixed

**Comment by ilmartyrk** [comment]
Reading:
Well written explanation of CSP : https://www.troyhunt.com/locking-down-your-website-scripts-with-csp-hashes-nonces-and-report-uri/
Issue with chrome and style-src error: https://bugs.chromium.org/p/chromium/issues/detail?id=546106

**Comment by ilmartyrk** [comment]
Sample config for development
```
{
    "csp": {
        "policies": {
            "default-src": ["self"],
            "img-src": ["*"],
            "script-src": ["self", "https://cdn.crowdin.com", "https://apis.google.com"],
            "style-src": ["self",  "https://fonts.googleapis.com"],
            "script-src-elem":["self"],
            "font-src": ["self", "https://fonts.gstatic.com"],
            "connect-src": ["self", "https://api.citizenos.com", "https://sentry.io", "https://graph.microsoft.com"],
            "base-uri": ["self"],
            "object-src": ["none"],
            "frame-src": ["https://p.citizenos.com", "https://accounts.google.com/", "https://docs.google.com"]
        },
        "reportUri": "https://api.citizenos.com/api/internal/report"
    }
}
```

`"script-src": ["self", "https://cdn.crowdin.com", "https://apis.google.com"],` -> Crowdin is used for debuging translations, this may be removed from production, apis.google.com is added to make google picker work to add attachments to topics.
            `"style-src": ["self",  "https://fonts.googleapis.com"],` -> fonts.googleapis.com is added to load fonts
            `"font-src": ["self", "https://fonts.gstatic.com"],` -> fonts.gstatic.com is added because fonts loaded by fonts.googleapis.com are from there
            `"connect-src": ["self", "https://api.citizenos.com", "https://sentry.io", "https://graph.microsoft.com"],` -> sentry.io is added for error reporting, grap.microsoft.com is added for loading onedrive file picker. This is a little risky if attachment file contains anything malicious
            `"frame-src": ["https://p.citizenos.com", "https://accounts.google.com/", "https://docs.google.com"]` -> accounts.google.com and docs.google.com are added for google picker. This also contains risk for malicious code from docs.google.com

**Comment by ilmartyrk** [comment]
Closing this issue, will remove report-only in two weeks

**Comment by ilmartyrk** [comment]
There are many issues caused by RIA-s token signing plugin that creates some inline script. This happens with firefox and safari

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
