### ISSUE TITLE
Localisation: /about - redirect /about to Citizen OS landing page

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#106]
**Overview**

No localisation for `/about` page - https://app.citizenos.com/ru/about

**TODO**

- [x] Get rid of `/about` page.
- [x] The sidebar "About" link should configurable. By default it should take to https://citizenos.com/product/
- [x] The old `/about` route should redirect to the configured link.

**Comment by tiblu** [comment]
@oksks We're not going to have a separate "About" page in the app, we're going to link it to Citizen OS.
