### ISSUE TITLE
EP: No "create link" button - can't create links with custom texts

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#110]
**Overview**

There is no "create link" button to enable creating links with custom texts. 
There used to be, but EP removed it in favor auto-detecting links.

**TODO**

- [ ] Find a way to enable links with custom text while keeping the auto-detect working. Also auto-detected links should be editable to create custom text.
- [ ] Check DOCX export, make sure links are exported.

**Comment by anettlinno** [comment]
Triage 51. Etherpad should have hyperlink plugins but we need to check if these are updated. Est. dev. time is 2 days.
Sending to development.

**Comment by ilmartyrk** [comment]
Possibly can use https://github.com/inicio/ep_embedded_hyperlinks

**Comment by KatiVellak** [comment]
Discussed on Triage, no further legal comments. User friendly approach.

**Comment by tiblu** [comment]
## Progress

* Seems the ep_embedded_hyperlinks is not maintained. There is a fork that seems to be maintained - https://www.npmjs.com/package/ep_embedded_hyperlinks2

### ep_embedded_hyperlinks2

- [x] NO links in HTML export
- [x] The link popup appears in a random place.
- [x] Hyperlink button location on toolbar not configurable.
- [x] Cannot remove a hyperlink from a piece of text. You can delete the text, but not just remove.
- [x] Beware to check copy-paste links from other pads, see if these work.

![image](https://user-images.githubusercontent.com/7405383/153236522-e5b9b9b6-9925-4c69-af4c-89d02c42b2b9.png)


Sent out a question to the maintainer about the future of the project - https://github.com/seballot/ep_embedded_hyperlinks2/issues/14#issuecomment-1033930879
and Citizen OS now maintains it - https://github.com/citizenos/ep_embedded_hyperlinks2

## TODO

In order of importance:

- [x] Links in HTML export
    - [ ] Tests!
- [x] Make sure copy-pasting links works.
- [x] UX - positioning of the link dialog
- [x] Remove a link
- [x] Make link button location configurable on the toolbar

**Comment by anettlinno** [comment]
Tested. Works nicely but hyperlink is hidden in the menu. I would recommend to change it to footnote or any other menu item that is less frequently used. Additionally I would prefer if  hyperlinked page would open in new window and I would still stay on COS topic. @ilmartyrk

**Comment by errotu** [comment]
Thanks a lot for your work! The updated version (with working HTML export) is not yet published on npm, is it? Are you planning to do so?
