### ISSUE TITLE
UX: Topic attachments - fix the topic attachments user experience

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#117]
**Overview**

The modal that pops up when adding attachments is confusing.
There is lack of information what the icons are (different upload methods), the "Save" button is in a strange place.

Here is a screenshot to explain it all:

![image](https://user-images.githubusercontent.com/7405383/48130246-aec54080-e294-11e8-9b0e-f352ae830ae7.png)

Here is how Trello does it, looks quite good to me:

![image](https://user-images.githubusercontent.com/7405383/48130382-28f5c500-e295-11e8-94e7-f39448ceabed.png)

**Related to**

* https://github.com/citizenos/citizenos-fe/issues/103

**TODO**

- [x] Get UX guys to redesign this so that it's clear to User that there are multiple sources to attach files from and what the modal is.
- [x] Implement the new designs in FE code
- [x] When I download an uploaded attachment, please make the file name same as in UI (https://github.com/citizenos/citizenos-api/issues/61)

**Comment by kevincrepin** [comment]
That's not really how it was designed though :) 
Popup: https://projects.invisionapp.com/d/main#/console/9829159/241242128/preview and in topic: https://projects.invisionapp.com/d/main#/console/9829159/213246467/preview

So I think there's no need for the button as the files get attached immediately, right?
