### ISSUE TITLE
Rahvaalgatus.ee notification

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#125]
**Overview**

As of 15.11.2018 Rahvaalgatus.ee will be having their own instance of Citizen OS. To promote Rahvaalgatus.ee and help Users find their Topics created in Rahvaalgatus.ee we should show Users a notification.

**TODO**

- [x] Show notification on screen as per design. Show ONLY if language is ET - https://projects.invisionapp.com/d/main#/console/9829159/331351007/inspect
- [x] User can close the notification
- [x] IF User closes the notification, store the information in a long living cookie so that the message is NOT displayed again.
- [x] Feature MUST be configurable. Default is OFF. Please keep the naming of the cookie and configuration keys consistent.
- [x] NO localisation, the text is only in ET.

![image](https://user-images.githubusercontent.com/7405383/48496021-d0489e00-e839-11e8-9d04-c83c32e437f0.png)

**Comment by tiblu** [comment]
Live.
