### ISSUE TITLE
LEGAL: User has to accept Terms of Use (TOU) & Privacy Policy (PP)

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#178]
**Overview**

By the law we have to make best effort that a User of the system has read and accepted the Terms of Use (TOU) & Privacy Policy (PP).  When a new TOU or PP is released, we have to notify User and User has to acknowledge the changes.

**TODO**

- [x] UX: A full screen popup after User logs in @kevincrepin 
    - Links to Terms of Use and Privacy Policy. Links present only for the document changes.
    - "ACCEPT" and "REJECT" buttons.
    - NO "just close" buttons.
    - "ACCEPT" closes the popup and User can continue using the service.
    - "REJECT" logs the User out and takes to homepage of the app.
- [x] API: Store/read latest TOU/PP version (that is EP revision of the TOU/PP document in Citizen OS)
- [x] API: Store/read accepted TOU version to DB (that is EP revision of the document). 
- [x] FE: Implement the popup, only shown if `currentVersion !== userAcceptedVersion`.

**Comment by tiblu** [comment]
**BLOCKED:** Requires the TOU & PP to be updated. That is input from Kati + @loorm.

**Comment by tiblu** [comment]
Linked to https://github.com/citizenos/citizenos-api/issues/102 - TOU& PP needs to be done beforehand.

**Comment by loorm** [comment]
Triage #4 - Margo will upload TOU into a COS topic.

**Comment by ilmartyrk** [comment]
@loorm is the correct topic https://app.citizenos.com/en/topics/7abdd244-d45b-40d3-997c-a6290d4e972c
@kevincrepin do you have any design ideas, or we'll just use our current available popup designs?

**Comment by loorm** [comment]
> @loorm is the correct topic https://app.citizenos.com/en/topics/7abdd244-d45b-40d3-997c-a6290d4e972c

No, this is API TOU. We need platform TOU. I have them from Kati, I believe. Need to create a public topic, copy them there and format to look good.

**Comment by kevincrepin** [comment]
@ilmartyrk something like this? https://projects.invisionapp.com/d/main#/console/17224475/366871835/preview

links need to open in a new tab of course, otherwise not much point in the accept/reject :)

**Comment by ilmartyrk** [comment]
https://github.com/citizenos/citizenos-api/commit/7738639de713eb3ff059b172ade08be3cbb28946

**Comment by KatiVellak** [comment]
Legally reviewed, during the discussions legal input provided.

**Comment by loorm** [comment]
Tested. Confirmed working.
