### ISSUE TITLE
LEGAL: Cookie policy notification

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#179]
**Overview**

As we all may have seen on many web pages, the cookie policy notification is required by the law.

**TODO:**

- [x] Kati & Co to provide the text
- [x] @oksks to organise the localisation.
- [x] UX: @kevincrepin To design the policy notificiation:
    - Does not have to be a full screen popup.
    - Does have to have "AGREE" button.
    - Does NOT have to have "REJECT" button as the text would go like "If you continue to use the site, you accept the policy".
    - Does have to have "CLOSE" button (X).
- [x] FE: Implement the notification. Once the policy is closed, make the best effort not to show it to the same User again. I guess we would store the state in a cookie, NOT in DB like for TOU/PP.

**Comment by tiblu** [comment]
**BLOCKED:** Requires Kati to provide the texts.

**Comment by tiblu** [comment]
@kevincrepin If we have the time and good will, maybe have a some "Clippy" like character to announce the cookie policy? Just to make a bit fun over the serious matter.

**Comment by kevincrepin** [comment]
@tiblu why a close button if they have to accept it?

**Comment by kevincrepin** [comment]
I think we should use the same notification as we had when RA left.
![cookie notification](https://user-images.githubusercontent.com/26792281/51752298-d96aac80-20bf-11e9-81da-c139947eeefa.png)

**Comment by tiblu** [comment]
@kevincrepin Sounds OK to me, can you put the assets to Invision?

**Comment by kevincrepin** [comment]
https://projects.invisionapp.com/d/#/console/9829159/343113827/preview there you go!

**Comment by loorm** [comment]
Triage #4 - Cookie policy exists in Estonian. Need to translate into English. Otherwise ready for deployment.

**Comment by ilmartyrk** [comment]
@loorm Where can i find this policy? If it's the one in drive is it still up to date or would need a review before it goes to translation.

**Comment by ilmartyrk** [comment]
https://github.com/citizenos/citizenos-api/commit/7738639de713eb3ff059b172ade08be3cbb28946

**Comment by KatiVellak** [comment]
Legally reviewed, during the discussions legal input provided.

**Comment by loorm** [comment]
Tested. Confirmed working.
