### ISSUE TITLE
CitizenOS topics page 

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#183]
**Overview**
Create a fixed topic box like "Keep It Clean Plan" and "10 Island Project" have, on the home page, that redirects to page containing topics about Citizen OS.

- [ ] UX design for home page box
- [ ] Create and trabslate box title and description
- [ ] Add new category Citizen OS

**Comment by ilmartyrk** [comment]
Not sure if still relevant

**Comment by kevincrepin** [comment]
It's not much work for us. If there's a value in having this we can do it. New platform isn't going to be out for a while.

@anettlinno what do you think?

**Comment by anettlinno** [comment]
I think we could do it. As talked with @ilmartyrk then the idea was that we could gather all the COS-related topics (user epic´s, product dev discussions, etc) into one "box". Let´s do it! :) 

We would need a beautiful "box" design from your side then, @kevincrepin

**Comment by TiinaDUX** [comment]
Hey! Update for topic page:  https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=1792%3A30149
We have created several color options to choose from.

**Comment by anettlinno** [comment]
> Hey! Update for topic page: https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=1792%3A30149 We have created several color options to choose from.

Thanks @TiinaDUX! We´ll choose from the proposed designs :)

**Comment by anettlinno** [comment]
Triage 52. Let´s use e-democracy category. Box will come on the second position on our platform. Text: E-democracy discussions with Citizen OS team. Sub-text: Join us in our platform development and e-democracy discussions. @seppviljar we would need your magic here to help us with the copy text :) 
We will vote over the design with team. 

Est. dev. time 1 hour. sending back to in prep.

**Comment by seppviljar** [comment]
The proposed text looks fine but I'd like to see it in action, thx :)

**Comment by anettlinno** [comment]
Triage 54. Made a team decision that we will go with blue "box" :) Need to create separate category Citizen OS. Est. dev. time 1 hour. Sending to development.

**Comment by tiblu** [comment]
**TODO:**

- [x] New UX   
- [x] New category
- [x] New route definition
- [x] Localization
    - [x] FE
    - [x] API (?)

**Comment by tiblu** [comment]
### Released - 13.12.2021

![image](https://user-images.githubusercontent.com/7405383/145843596-7945b34f-0a39-4bda-b2c4-46ba81fd87ff.png)

**Implementation notes:**

* New category "Citizen OS".
* Every Topic with "Citizen OS" category will be shown on the Citizen OS category page - https://app.citizenos.com/en/citizenos
* Design is a bit different from the UX mentioned above. To comply with the designs proposed in this item (https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=1792%3A30149), I would have had to change every existing square. I decided to keep consistency by modifiend the designs to match the existing ones.
* Fixed coloring of squares for some other categories.
* Actual time spent 2h - modification of the design for consistency, helping other categories out.

**Comment by anettlinno** [comment]
Thanks, @tiblu! Could you please update the text as it was proposed: E-democracy discussions with Citizen OS team. Sub-text: Join us in our platform development and e-democracy discussions.

Thanks! :)

**Comment by tiblu** [comment]
> Triage 52. Let´s use e-democracy category. Box will come on the second position on our platform. Text: E-democracy discussions with Citizen OS team. Sub-text: Join us in our platform development and e-democracy discussions. @seppviljar we would need your magic here to help us with the copy text :)

@anettlinno Done!

![image](https://user-images.githubusercontent.com/7405383/146004816-34b0aad8-b74f-4f31-b5ca-fcb5ea50353b.png)
