### ISSUE TITLE
Move buttons in dialog windows from upper right corner to below

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#234]
**What is the problem?**
In dialog windows, the buttons appear in upper right corner. This is an unconventional placement.

**Why is this a problem?**
Users not used to seeing buttons there, rather at the bottom of dialog windows. May not find the button and lose made changes, when they simply close the dialog. Else, it just takes them a suboptimal amount of time to find the button.

**Possible solution**
N/A. Just need to think about what the best solution is.

**Comment by kevincrepin** [comment]
@loorm So working on this at the moment and it definitely ties into "bigger stuff". Below is an outline of how I see the future of the dialog window usage:

**Still dialog windows**
* Login
* Warnings that require user input, ie.
    * delete topic
    * delete user
* Reported topic
* Voting
    * Hard ID method
    * Delegation

**Not anymore in dialog windows**
* Topic Settings
    * general settings
    * tags
    * invitation
    * sharing
    * user rights
    * group rights
* Account creation
    * let’s use more space to also give some insights into why an account is a good thing
* Account settings
    * general settings
    * privacy
    * multiple accounts
* Group creation
* Language selection

So where does the content exist if not in the dialog windows? That's where the "bigger stuff" comes in, also taking cues from our kickoff meeting which revealed other issues like the topic settings being spread all over the place, etc.

I'm working now on a way to solve all those issues in one go, because they're all tied together.

**Comment by kevincrepin** [comment]
Added updated examples here: https://projects.invisionapp.com/d/main#/console/17224475/358860171/preview

- Tabs are divided along the entire width
- action button is in the bottom and the label changes according to the section. So for example in topic settings you save the changes, but in the invite section you send invites.
- Height behaviour (for the time being): Let's let the window expand in height until it would exceed the window's height. At that point the "header" and "footer" get fixed and the "content" becomes scrollable. Indicated these section also on the design for clarity.

**Comment by loorm** [comment]
@oksks Please see if this is OK as an intermediate solution from l10n perspective. It creates a bunch more room for Finnish and other longer languages in the tab titles. Design will not break as easily.

**Comment by oksks** [comment]
@loorm looks great, thanks!

**Comment by loorm** [comment]
Visuals are in invision. Need to implement. Moving to development.

**Comment by tiblu** [comment]
**TODO:**

- [x] Create the footer section for dialogs
    - [x] Topic Settings
    - [x] My Account (Account settings)
    - [x] Group settings
    - [x] Vote delegation
- [x] FIX BUG - related to screen size - ![image](https://user-images.githubusercontent.com/7405383/70994777-9f3f3a80-20d7-11ea-9079-7bd724cb4ca7.png)

**Comment by tiblu** [comment]
Agreed with @loorm that we're doing minimum that needs to be done to move the buttons.

In general the code related to dialog windows has a lot of duplication and variety thus lacking consistency.

Despite that fact, we're going to post-bone the refactoring.

**Comment by ilmartyrk** [comment]
Updated modals listed in the TODO https://github.com/citizenos/citizenos-fe/commit/1070654739498a014ee5971de0ace4532dcb6fda

**Comment by loorm** [comment]
Tested. Confirmed working. Thank you!

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
