### ISSUE TITLE
Topic Settings -> Invite - auto complete results to mark members that are already in the Topic

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#254]
**Overview**

When User opens up the Invite tab in the Topic Settings, we MAY want to show and enable modification of existing member list in that Topic.

There was an attempt to make a simple implementation of that, but that was broken and got removed (https://github.com/citizenos/citizenos-fe/issues/253). There is no such easy way to do it. IF we want it, we need to go deeper.

**TODO**

- [x] Do we or do we not want to show existing member list in that Topic? NO
- [x] IF YES, what would the UX be like?
- [ ] Auto-complete to mark Users in the results that already have access to this topic

**Comment by loorm** [comment]
Triage #4 - will not start showing user list in dialog window. However, will add a sign in autocomplete list to users, who are already added to topic.

**Comment by tiblu** [comment]
**Implementation notes**

I see 2 options:

* Do the marking in frontend code by fetching member list once and comparing against auto-complete results
* Do the marking in the back-end by fetching AND caching the member list.

First option is cheaper I guess.

**Comment by tiblu** [comment]
@loorm @kevincrepin I guess we don't have UX for this? That is the sign for the auto complete list? Moving to "In preparation".

**Comment by loorm** [comment]
@tiblu Perhaps it's easier and less costly, if we let the user "send" invites to everyone they want from a complete list of users. However, when our back end code does the actual sending, it checks for existing users and does not send an existing user another invite to join the same topic. WDYT?

Ideally, we would notify the inviting user of this as well, but it's not critical. The goal is to have the invited user in the topic. If they are in the topic, the goal has been reached. Whether they joined recently or were a member before should be irrelevant to the inviting user.

**Comment by loorm** [comment]
@tiblu Can you please give and update on the status of this issue? It seems to me like we have everything necessary to move it to Triage?

**Comment by tiblu** [comment]
@loorm 
> @tiblu Perhaps it's easier and less costly, if we let the user "send" invites to everyone they want from a complete list of users. However, when our back end code does the actual sending, it checks for existing users and does not send an existing user another invite to join the same topic. WDYT?

I agree and propose:

* IF User has already accepted the invite, we SHOULD NOT re-send.
* IF User has already accepted the invite, BUT with fewer permissions (ex: has read, but invite would be admin), upgrade permissions BUT NOT re-send e-mail.
* IF User has NOT accepted the invite, we SHOULD re-send invite, cause the User MAY have missed the previous one.

IF you agree with the solution, we can prioritize this.

**Comment by loorm** [comment]
@tiblu I agree. Assigning to Triage.

**Comment by loorm** [comment]
Triage 23. Ready for development. Prioritizing. Estimated dev time 1 day.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.
