### ISSUE TITLE
Create custom 500 page

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#293]
Custom page which asks people to check out our technical Twitter feed ot find out what's going on.

**NOTES:**

* The links of the page have to be configurable for in-house deployments.

**Comment by loorm** [comment]
@tiblu What do we need for this? A design from Kev? Can it be translatable?

**Comment by tiblu** [comment]
@loorm 

We need:

* Twitter account - CitizenOSStatus or CitizenOSDev or CitizenOSHeartbeat or...
* Agree on the exact information we want to display.
* Designs from Kevin.

**Comment by loorm** [comment]
1. The Twitter feed we have https://twitter.com/CitizenOSStatus. We're not actively using it, but it's there.
2. @tiblu Did you mean information we want to display on the 500 page or in the feed?
3. @kevincrepin 

In terms of the info on it, I would say:
- information, that a server error has occured
- an apology
- link to our technical twitter feed
- customer support contact to notify us or ask us for info

**Comment by loorm** [comment]
Ping @kevincrepin

**Comment by kevincrepin** [comment]
Here you go! https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=685%3A24364

**Comment by loorm** [comment]
We have the design. Moving this to Triage.

**Comment by tiblu** [comment]
> 2\. @tiblu Did you mean information we want to display on the 500 page or in the feed?

I meant on the 500 page itself. When it comes to the feed, I guess that's up to us. 
Also, I think the Twitter link MAY need to be configurable for in-house deployments.

Looks good to me.

**Comment by anettlinno** [comment]
Triage 45. Sending 500 page to development. Est. dev. time 4h. Twitter feed investigation timebox 1h.

**Comment by KatiVellak** [comment]
No legal impact, nice design from Kevin.

**Comment by tiblu** [comment]
### TODO

- [x] Create a custom 500 page - NO external references! (citizenos-fe/public/views/500_independent.html)
    - [x] https://citizenos-prod.s3.eu-west-1.amazonaws.com/error_pages/500_independent.html
    - [x] https://citizenos-prod.s3.eu-west-1.amazonaws.com/error_pages/503_independent.html
- [x] Configure custom 500 page in Cloudflare? **DID NOTHING:** Requires PRO account - https://support.cloudflare.com/hc/en-us/articles/200172706-Configuring-Custom-Pages-Error-and-Challenge-.  Not sure it is worth doing it now either. For 500-s and maintenance we can configure a page in Heroku.
- [x] Configure custom 500 page in Heroku - https://devcenter.heroku.com/articles/error-pages
- [x] Make an FE route for 500 and show the same page - **DID NOT DO** - Reason being - if the API returns 500 and we redirect User to a generic error page, the User cannot provide any meaningful info about what happened on the screen. It is best to show generic error bar on the top and leave the User where they were.

**Comment by tiblu** [comment]
**DONE:**

Implementation notes:

* Created 2 different independent error pages in Citizen OS FE project - 500_independent.html and 503_independent.html.
* Put them to AWS public bucket to be referenced where needed:
    * https://citizenos-prod.s3.eu-west-1.amazonaws.com/error_pages/500_independent.html
    * https://citizenos-prod.s3.eu-west-1.amazonaws.com/error_pages/503_independent.html
* Configured and tested the error pages ONLY for Citizen OS FE PROD and TEST app in Heroku - `ERROR_PAGE_URL` and `MAINTENANCE_PAGE_URL` (https://devcenter.heroku.com/articles/error-pages).
    * Did not make sense to configure these for API and EP as these serve JSON, no sense in returning HTML. IF any of them is broken, FE will show its errors.

![citizenos_500_maintenance](https://user-images.githubusercontent.com/7405383/143599514-da5ab3d2-b403-44a2-90b6-0c1a5a97255b.png)

![citizenos_503_maintenance](https://user-images.githubusercontent.com/7405383/143599518-e2af02f9-14d9-4494-abee-0a0972654af8.png)
