### ISSUE TITLE
Add possibility to choose rights level  for join link.

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#311]
**What is the problem?**
Join links are short and handy for sharing vs the huge topic links copied from the browser. However, when using the join link, the user is automatically set to rights level "view". I had this case - I wanted to co-create a topic with about 12 people. I created the topic, then sent out the join link. Then, as people joined the topic, I had to keep going back to the user list and upping their level so that they could edit topic text. The invited users had to join, then text me in another app that they have joined, for me to know when to go and up their user rights level.

**Why is this a problem?**
A LOT of unnecessary clicking, communication and time delay.

**Possible solution.**
When sending the join link, let me choose the rights level that users who join via the link get. NB! The available rights level needs to be either equivalent to my own rights level or below, but not higher. In other words, when I have edit rights, I can't send out a join link, that has a user joining in admin rights.

![link_rights](https://user-images.githubusercontent.com/22661743/67851656-8ec90580-fb13-11e9-9358-04b8dd550994.JPG)

**Comment by loorm** [comment]
Triage 14 - many links can be "active" at the same time. To some people, you send a link with "edit" rights, to others with "read" rights. Both remain valid. If you create a new link, invalidate only the former link of those rights. @kevincrepin - please create a visual for selecting the rights of a join link. 

@tiblu added, that we should make links human readable /join/lendoravate-kaitse-18947598732?r=edit

**Comment by kevincrepin** [comment]
@loorm 
![sharing](https://user-images.githubusercontent.com/26792281/68123889-c15d6e80-ff16-11e9-904c-5e90074a1879.png)

**Comment by tiblu** [comment]
Margo what you think?

**Comment by loorm** [comment]
Looks good.  Only perhaps the "Copy link" button would need to be at the end of the link line? Or maybe there's a good reason to keep it where it is, that didn't occur to me...

**Comment by loorm** [comment]
Triage 15: @kevincrepin Mikk and I both think, that the "Copy link" button should be on the same line as the link. Can we persuade you to move it? :)

**Comment by loorm** [comment]
Triage 15: linked to #325

**Comment by kevincrepin** [comment]
@loorm @tiblu I can be persuaded to do almost anything: https://projects.invisionapp.com/d/main#/console/17224475/394976236/preview

Thinking to remove the label refresh and replace with icon? Thinking that the url and this label might easily overlap in other languages.

**Comment by loorm** [comment]
@kevincrepin The link in your previous post stopped working with the shuffle you did yesterday in the InVision projects. Can you please post a new relevant link?

**Comment by kevincrepin** [comment]
Ah yes, of course: https://projects.invisionapp.com/d/main#/console/9829159/404592933/preview

**Comment by loorm** [comment]
Triage 18: Need a decision on:
- sharing a single link or multiple links
- can user understand, that QR sharing applies to the same link + rights as above
- which link is social shared

Dev time ETA: 2 days.

**Comment by loorm** [comment]
Decisions:
- There will be just one link. The link does not change. It remains the same, whatever access rights are associated with it. Hence, the rights level an also be changed after the link has already been shared. Whatever the current access level setting is, it applies to everyone who use the link to access the topic, IF they don't have prior access to the topic. If user has prior access to topic with "edit" level and the link has "read" level, when user clicks the link, they get to the topic with their existing rights level (i.e. "edit").
- QR Code should be adjacent to the link or otherwise design whould make it clear, that the QR code contains the same share link.
- social sharing buttons should only be visible for public topics and give the same type of access, that a non-logged in user gets when clicking onto a public topic.

**Comment by loorm** [comment]
We have a design. We have the feature description. Moving to Triage.

**Comment by loorm** [comment]
NB! Once this issue is closed, have a look at https://github.com/citizenos/citizenos-fe/issues/325

**Comment by anettlinno** [comment]
Triage 45. Successfully replicated. Add confirmation pop-up to create new join link. Est. dev. time 6h. Sending to development.

**Comment by ilmartyrk** [comment]
Administrative tasks:

- [ ] Update CHANGELOG files
- [ ] Inform marketing of new feature(s)
- [ ] Inform localization on new translations

**Comment by KatiVellak** [comment]
Legally reviewed and discussed, no impact.

**Comment by ilmartyrk** [comment]
Also implement social share from https://github.com/citizenos/citizenos-fe/issues/361

**Comment by tiblu** [comment]
## TODO

### The Main Quest - Share/join links 
- [x] New Models/tables for join links. `:tokenJoin` & `level` - **DONE:** TopicJoin
- [x] New API `POST /api/topics/:topicId/join` to (re)generate join link for a Topic. **TODO** Naming!
- [x]  Update API `POST /api/topics`
- [x] New token generation for fresh Topic
- [x]  Update API `GET /api/topics/:topicId` AND `GET /api/topics` and others that give out TokenJoin info.
- [x] `GET /api/v2/search` fix returning of join token (replace: "tokenJoin") with `{ join: token, level}`
- [x] API DOCS: Update docs, seems manual work right now :( - **DONE:** TBH the docs seems to contain invalid syntax and info, specially when it comes to "security" part. Just added my endpoints there, postboned fixing all of it as we need to find a better way of generating docs so that it is up to date.
- [x] Update API `POST /api/topics/join/:token` to use new TokenJoin data.
    - [x]  Make sure Joining with a link DOES NOT OVERWRITE existing permissions
- [x] Activities in all of the API-s!
    - [x] `POST /api/topics/join/:token` - User joined a Topic - **DONE: no change**
    - [x] `PUT /api/users/:userId/topics/:topicId/join` - User generated a NEW join token WITH level
    - [x] `PUT /api/users/:userId/topics/:topicId/join/:token` - User set a new level for an EXISTING token
- [x] Update UX
    - [x] Assets
    - [x] Dropdown
    - [x] UI updates (layout etc)
    - [x] Warning that regenerating link will invalidate the previous links
    - [x] Mobile friendlyness
    - [x] ACTIVITIES - make sure the feed looks good
        - [x] Current ones used, and are to be kept:
            - [x] `"ACTIVITY_USER_UPDATE_TOPIC_ACTIVITYGROUP": "User <em>{{userName}}</em> and <em>{{groupCount}}</em> others have updated topic <em>{{topicTitle}}</em>"`
            - [x] `"ACTIVITY_USER_UPDATE_TOPIC_USERACTIVITYGROUP": "User <em>{{userName}}</em> has made <em>{{groupCount}}</em> updates to topic <em>{{topicTitle}}</em>"`
            - [x] `ACTIVITY_FEED.ACTIVITY_USER_UPDATE_TOPIC`
        - [x] ADD NEW:
            - [x] Activity feed needs to return `origin.topicTitle` & `object.topicTitle` where appropriate (https://github.com/citizenos/citizenos-api/commit/e80c1ae4f6e13dd29189b64f67ecfb9f1728b7fa#diff-d74850df717ca385b9a660fff111fd8c800cb036b70a05090cb0630dded38713) 
            - [x] `ACTIVITY_FEED.ACTIVITY_USER_UPDATE_TOPICJOIN_ACTIVITYGROUP`
            - [x] `ACTIVITY_FEED.ACTIVITY_USER_UPDATE_TOPICJOIN_USERACTIVITYGROUP`
            - [x] `ACTIVITY_FEED.ACTIVITY_USER_UPDATE_TOPICJOIN`
         - [x] FIX BUG: TopicMemberUsers level change shows no Topic title - ![image](https://user-images.githubusercontent.com/7405383/136226504-eae17646-1442-4736-a7ca-bce618ca0452.png) - CAUSE: Chief Archeologist @ilmartyrk  found out that "topicTitle" has been lost in evolution - https://github.com/citizenos/citizenos-api/commit/e80c1ae4f6e13dd29189b64f67ecfb9f1728b7fa#diff-d74850df717ca385b9a660fff111fd8c800cb036b70a05090cb0630dded38713
    - [x] ACTIVITIES - should only ADMIN members see "TopicJoin" activities? Mask the sensitive info? **DONE:** We agreed with @ilmartyrk  that we will mask the info - https://github.com/citizenos/citizenos-api/commit/c0278d8a19cba0a24ece8c6d7dff3882d2ccc344
- [x] Link format changes:
    - [x] New: `https://app.citizenos.com/topics/join/:token`. 
    - [x] Old: `https://app.citizenos.com/join/:token`, BUT keep support for BW comp!
- [x] DB migration:
    - [x] CREATE TABLE "TokenJoins" 
    - [x] Generate "TokenJoin" for every existing Topic with default level - READ
    - [x] ALTER TABLE "Topics" DROP COLUMN  "tokenJoin
    - [x] Migrate old "Topic.tokenJoin" activities to new "TopicJoins" activity.
         - [x] ~~"User joined a Topic" activity - update "context", rest stays the same.~~ **WILL NOT DO** - Only "context" difference will not change feed translation and allows us to differ pre-migration joins.
         - [x] For each existing "Topic.tokenJoin" modification Activity we need to generate a new format where "TopicJoin" object is modified. 
         - [x] ~~Delete "topicJoin" property from every Activity that has "Topic" object in it.~~ **WILL NOT DO as agreed with** @ilmartyrk

### Side quests

- [x] Social Share - https://github.com/citizenos/citizenos-fe/issues/361 - ONLY FOR PUBLIC TOPICS
- [x] QR Code download as PDF - **SEPARATED OUT:** https://github.com/citizenos/citizenos-fe/issues/832
- [x] Slug support. Slug will only be for SEO and human readability. Slug can change over time. Slug will be compiled from the Topic title, when title updates, all new links will have new slug, but that WILL NOT break old links as only `:tokenJoin` is used. For example title "Citizen OS Topic moderation" becomes `citizen-os-topic-moderation`. - **NOT IMPLEMENTED DUE to me not seing all that much value in it**

### Administrative tasks

- [x] Update CHANGELOG files
- [x] Inform marketing of new feature(s)
- [x] Inform localization on new translations

**Comment by tiblu** [comment]
@loorm @ilmartyrk 

Need your input:

**Q1**
Current solution: Only ADMIN members of the Topic can regenerate join link.
New solution: All members can regenerate join link?

**Q2**
Current solution: No LEVEL for the join link
New solution: All members can change LEVEL of the existing join link, BUT the level is at most the same LEVEL you have for the Topic?

**Comment by ilmartyrk** [comment]
Keep current solution, only admins can create new links and change permissions. Letting the link handling free would probably create a total mayhem.

**Comment by anettlinno** [comment]
> @loorm @ilmartyrk
> 
> Need your input:
> 
> **Q1**
> Current solution: Only ADMIN members of the Topic can regenerate join link.
> New solution: All members can regenerate join link?
> 
> **Q2**
> Current solution: No LEVEL for the join link
> New solution: All members can change LEVEL of the existing join link, BUT the level is at most the same LEVEL you have for the Topic?

Q1: Agree with Ilmar that only admin members can regenerate the link
Q2: AND that only admins can change the permission of level. If user had higher level to the topic then the one that was newly given by admin (previously "edit" and with new link "read") then the higher level ("edit" in this example) remains. New Users will join with the "reading" permissions.

**Comment by tiblu** [comment]
@loorm @ilmartyrk @anettlinno 

To recap:

* ONLY "admin" members can regenerate link.
* ONLY "admin" members can modify the level of an existing link.
* When User visits a Topic with join link that he/she has already access, he/she can only get higher level of permission, never downgraded.

**Comment by tiblu** [comment]
## Deployment - Main Quest - Share/join links (https://github.com/citizenos/citizenos-fe/issues/311#issuecomment-920907518)

### TEST

- [x] DB migration
- [x] API
- [x] FE

### LIVE

- [x] DB migration - pre-deploy backup: b2128
- [x] API
- [x] FE
- [x] DB - update live schema file `/config/db/database.sql` - https://github.com/citizenos/citizenos-api/commit/217634ee671269358fc758323b04e97885c4ce2d

**Comment by tiblu** [comment]
## FEATURE RELEASED: Share/join links with specific permission

![topic_share_link_conf_screen](https://user-images.githubusercontent.com/7405383/136587252-7910dc2f-1aee-4e57-87d8-5aa705b9f5e3.PNG)

## Implementation notes:

* ONLY "admin" member of the Topic can regenerate and mofiy a share/join link.
* User will be presented with a confirmation dialog that warns about the consequences of changing the link.
* IF User accesses a Topic with a share/join link BUT is already a member of the Topic we DO NOT update User permissions.
* Old share/join links (for ex: https://app.citizenos.com/join/r0TIsRPW) remain working by left padding the token with '0000' and redirecting to https://app.citizenos.com/topics/join/0000r0TIsRPW.
* ALL Activities related to share/join link token regeneration have the token masked, only first and last 2 chars are visible to everyone. This is because we have no Topic permission level based filtering in the activity feed, that is - all members of the Topics see all the Topics activities. In order to hide the token from non-admin Users, but still provide useful debugging info on the token changes, we show limited characters.

**Comment by tiblu** [comment]
@tiblu  NOTE TO SELF: Update changelog of CitizenOS - FE!

**Comment by anettlinno** [comment]
@tiblu user view is broken:
<img width="603" alt="copy link" src="https://user-images.githubusercontent.com/45175679/136742705-78c3ecc5-2850-483e-8ec0-c48c3aa75478.png">

**Comment by tiblu** [comment]
> @tiblu user view is broken: <img alt="copy link" width="603" src="https://user-images.githubusercontent.com/45175679/136742705-78c3ecc5-2850-483e-8ec0-c48c3aa75478.png">

@anettlinno Works on my screen.

![image](https://user-images.githubusercontent.com/7405383/136752211-77804477-b9c4-4728-808a-720cbb80a4cb.png)

**Comment by anettlinno** [comment]
@tiblu works on my screen now too :)) Tested on desktop and phone 👍

**Comment by tiblu** [comment]
## Side quest 1 - Social Share

* Facebook share link format - `https://facebook.com/sharer/sharer.php?u=https://www.err.ee/1608368166/koalitsioon-plaanib-energiahindade-kompenseerimist&title=&quote=Koalitsioon%20plaanib%20energiahindade%20kompenseerimist&description=&image=`
* Twitter share link format - `https://twitter.com/intent/tweet?url=https://www.err.ee/1608368166/koalitsioon-plaanib-energiahindade-kompenseerimist&related=err_ee&hashtags=ERR&text=Koalitsioon%20plaanib%20energiahindade%20kompenseerimist%0A%0A`
* Linkedin - `https://www.linkedin.com/shareArticle?title=Koalitsioon%20plaanib%20energiahindade%20kompenseerimist%0A%0A&url=https://www.err.ee/1608368166/koalitsioon-plaanib-energiahindade-kompenseerimist`

**Comment by anettlinno** [comment]
Tested FB sharing. System takes the topic url, but shows COS intro (or landing) page information. It should show topic information (header, picture, first paragraph). 

In share window: 
<img width="412" alt="FB1" src="https://user-images.githubusercontent.com/45175679/137140651-aaf18c99-9185-45fb-885b-8ece470924e3.png">

In FB feed:
<img width="397" alt="FB2" src="https://user-images.githubusercontent.com/45175679/137140786-fe031811-5bed-46aa-beb8-f1aab1e886ed.png">

**Comment by tiblu** [comment]
## FEATURE RELEASED: Social share

![image](https://user-images.githubusercontent.com/7405383/137140894-7694a18a-75fc-411d-ae5a-701449961c06.png)

## Implementation notes:

* Implemented using https://github.com/720kb/angular-socialshare

**Comment by tiblu** [comment]
> Tested FB sharing. System takes the topic url, but shows COS intro (or landing) page information. It should show topic information (header, picture, first paragraph).
> 
> In share window: <img alt="FB1" width="412" src="https://user-images.githubusercontent.com/45175679/137140651-aaf18c99-9185-45fb-885b-8ece470924e3.png">
> 
> In FB feed: <img alt="FB2" width="397" src="https://user-images.githubusercontent.com/45175679/137140786-fe031811-5bed-46aa-beb8-f1aab1e886ed.png">

@anettlinno THE ROBOTS see what a User would see when clicking the link - the login screen as its a PRIVATE topic we cannot show more data. I am sending Topic title and url to the share url of the service (FB, Twitter, LinkedIn). How and if they use the info, thats up to the service provider.

**Comment by tiblu** [comment]
## Side quest 2 - Download QR code PDF

![image](https://user-images.githubusercontent.com/7405383/137142015-b2b0f7f9-1d04-46a4-96f0-78f3e65b50de.png)


@anettlinno "Download QR code PDF" Whats the use case of this feature? Who and how would use it?

**Comment by anettlinno** [comment]
@tiblu I shared public topic, this one here: https://app.citizenos.com/topics/join/0000hdT7wc4K 

I just checked that if I copied topic URL then in FB it is displayed correctly (see picture below). But if I take copy with Link or Social share then I get COS general information. 

<img width="391" alt="FB3" src="https://user-images.githubusercontent.com/45175679/137142716-659347b4-d841-4f5a-89b0-2187e47ee1b0.png">

With public topics and shares it is super important that topic header, picture and first paragraph would be included.

**Comment by tiblu** [comment]
> @tiblu I shared public topic, this one here: https://app.citizenos.com/topics/join/0000hdT7wc4K

I see, it's related to how join links for public topics are handled. There is a separate issue to improve this UX - https://github.com/citizenos/citizenos-fe/issues/405

**Comment by anettlinno** [comment]
> > @tiblu I shared public topic, this one here: https://app.citizenos.com/topics/join/0000hdT7wc4K
> 
> I see, there is a separate issue to improve this UX - #405

@tiblu 405 is not quite the same as currently the issue is only about how the shared public topic is displayed in social media (FB) but 405 is about if people needs to log in to see the topic (after they click on the link).

**Comment by tiblu** [comment]
@anettlinno 
The information you see on the provider side (FB, LI) seems to be compiled by THE ROBOT visiting the URL you are tryhing to share.

The issue seems related as THE ROBOT experiences and sees the same info that a non-logged in User. IF User sees nothing about the Topic, THE ROBOT sees nothing. So if we fix the experience so that a User sees PUBLIC topics info WITHOUT logging in after clicking /join link, the ROBOT would see the info to render the preview.

I have a strong feeling that we cannot provide the info with the share link API parameters because FB, LI want to battle clickbait shares - that providing totally different context to that behind the link. So what they do they generate most of the preview by visiting the page url provided and generating the preview based on SEO tags.

**Comment by anettlinno** [comment]
> ## Side quest 2 - Download QR code PDF
> ![image](https://user-images.githubusercontent.com/7405383/137142015-b2b0f7f9-1d04-46a4-96f0-78f3e65b50de.png)
> 
> @anettlinno "Download QR code PDF" Whats the use case of this feature? Who and how would use it?

@tiblu I don´t know the use case or user story of this request but I tested that if you press CTRL + P then in print preview it looks nice -- you´ll get the content and QR code in pdf if needed. So it works well in my mind :) Only thing is that if users don´t know how to use print preview in your browser window.... 

<img width="845" alt="QR" src="https://user-images.githubusercontent.com/45175679/137146216-f54e3657-6e8c-402c-8128-00f04f89e122.png">

@kevincrepin designed the "Download QR code PDF" maybe he knows what´s the story behind that request :)

**Comment by kevincrepin** [comment]
Margo was behind this request :D 

But I can see its use as a printout that gets shared physically (on wall for example) so people can just scan the QR code to get the link to the topic. But not sure if there's a need for the QR code to be shown in the dialog...

**Comment by tiblu** [comment]
> "Download QR code PDF" Whats the use case of this feature? Who and how would use it?

![image](https://user-images.githubusercontent.com/7405383/137357973-cf242115-e7db-4568-a29c-448b3bd23fc1.png)

@loorm Can you shed some light into the  "Download QR code PDF" feature? Who and how would use it?

**Comment by anettlinno** [comment]
> Margo was behind this request :D
> 
> But I can see its use as a printout that gets shared physically (on wall for example) so people can just scan the QR code to get the link to the topic. But not sure if there's a need for the QR code to be shown in the dialog...

Yes, your are right, Kevin! One of the user cases is when people want to initiate topic in COS and invite people to the discussion by printing it on the poster (and putting the poster on the University wall for example). The other user case is when people are having public demonstration and want to print the topic on the poster. In these cases user needs only the QR code that is printable. I´m just thinking if the topic headline should be there too or not.. .

**Comment by loorm** [comment]
What she said.

**Comment by tiblu** [comment]
> > Margo was behind this request :D
> > But I can see its use as a printout that gets shared physically (on wall for example) so people can just scan the QR code to get the link to the topic. But not sure if there's a need for the QR code to be shown in the dialog...
> 
> Yes, your are right, Kevin! One of the user cases is when people want to initiate topic in COS and invite people to the discussion by printing it on the poster (and putting the poster on the University wall for example). The other user case is when people are having public demonstration and want to print the topic on the poster. In these cases user needs only the QR code that is printable. I´m just thinking if the topic headline should be there too or not.. .

Thanks for the explanation.

Would it suffice if I open up a new page with big QR code and whatever info needed on the screen INSTEAD OF a downloadable PDF?
Generating a PDF for download is somewhat expensive and a User can "Print" a PDF - that is, choose "Print" and destination "Safe to PDF". 

![image](https://user-images.githubusercontent.com/7405383/138065822-2914c332-b655-44b4-9b29-414d9a9ab304.png)

**Comment by anettlinno** [comment]
@tiblu do I understand correctly that what you propose is that when user clicks on the "Download QR code" then new window with QR code will open and user has to go through the pdf. printing process? I don´t understand what you mean by re: _PDF for download is somewhat expensive_ but I think if ever possible, we should provide user ready-to-use PDF solution here :) 

Please correct me if I misunderstood and your proposed solution was something else.

**Comment by kevincrepin** [comment]
I made a small change so that we don't show the QR code in the popup anymore and we have some explanation of how the QR code can be used. Then a generate QR code link will open it up in a separate page from which people can use the print as pdf functionality from the browser.

https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=744%3A25203

**Comment by anettlinno** [comment]
> I made a small change so that we don't show the QR code in the popup anymore and we have some explanation of how the QR code can be used. Then a generate QR code link will open it up in a separate page from which people can use the print as pdf functionality from the browser.
> 
> https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=744%3A25203

I really like this solution!

**Comment by tiblu** [comment]
@anettlinno Closing this exploded task. 
Created a new task for the QR code and PDF experience - https://github.com/citizenos/citizenos-fe/issues/832. Reason being the original task scope goint too big with unrelated stuff, also it makes sense to do these at once for Groups and Topics at once. Also mentioned that assumption for this task is #311 and #325 to be completed.

What was actually done in this task is in this comment  - https://github.com/citizenos/citizenos-fe/issues/311#issuecomment-920907518

**Comment by anettlinno** [comment]
> @anettlinno Closing this exploded task. Created a new task for the QR code and PDF experience - #832. Reason being the original task scope goint too big with unrelated stuff, also it makes sense to do these at once for Groups and Topics at once. Also mentioned that assumption for this task is #311 and #325 to be completed.
> 
> What was actually done in this task is in this comment - [#311 (comment)](https://github.com/citizenos/citizenos-fe/issues/311#issuecomment-920907518)

Thanks a lot, @tiblu! 🥇 
I tested it one more time, everything works nicely and made one recommendation in #833
