### ISSUE TITLE
Add "question" as a third category into the debate

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#329]
Questions are a natural part of any debate or discussion. They are not pro or con arguments and having to mask them as one is incorrect. We need to add a third category to the debate, called "Question".

**Comment by loorm** [comment]
Actually, the name of this probably would need to be "question / info". This is a longer discussion, but let's get going. We need this, because natural human discussion does not only contain pro and con arguments, it also has questions, answers and neutral background information or comments. We need to account for this, but bringing in a new category will create system-wide implications, of course.

@kevincrepin At any point in our design history, have you played around with an idea, of how this might look visually clear in the discussion?

@ilmartyrk Not a high priority, but we could start listing things here, that are going to be influenced, when we bring in a new category of posts in discussion.

**Comment by loorm** [comment]
Ping @kevincrepin @ilmartyrk

**Comment by ilmartyrk** [comment]
Adding new types to API side is easy as we just need to add new types after pro and con. FE side is probably more difficult, but @kevincrepin can elaborate on that

**Comment by loorm** [comment]
This is a part of a card called "Advanced collaborative decision-making" on the Big Picture Board. This issue here is not yet intended for development, it is a discussion issue.

**Comment by kevincrepin** [comment]
WDYT of this? https://www.figma.com/proto/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?page-id=2%3A16032&node-id=0%3A4081&viewport=299%2C48%2C0.5&scaling=min-zoom

Instead of having several buttons let's have one "post as" and all options under it. They are still colour coded in the dropdown menu for easy recognition.

**Comment by ilmartyrk** [comment]
@loorm thanks, for notifying. Anyway, had a look at the code on API side, the changes needed there are really small and easy to implement. 
On the UI side I believe that we should visually separate these from arguments, maybe create another tab? 

Also would it make sense if me add some-kind of a marking possibility if question is answered or not? We have the upvote/downvote functionality, but we could add an option for the asker to give visual feedback if he/she got the answer for the question.

@kevincrepin this input is really clear, using the colors in select, 👍

**Comment by loorm** [comment]
I like the design. I wouldn't add two new types of conversation component, though, just one. And I definitely don't want to call it a "comment", because then everyone will simply take the easy way out and instead of posting arguments, they'll post comments, because that's what they're more used to. And that's what we don't want them to do.

How about we call it "Point of Information"? That's what we call them in debates. Up top, where we count things, (pro 8; con 4) we can have poi: 3.

There will be no need to indicate, if the question has been answered, because this is not a Q&A session, where someone knows the answers. Points of Information are sometimes references to evidence, sometimes philosophical or rhetorical questions and sometimes just witty remarks intended to make a point.

Their length needs to be severly limited, to avoid people using POIs instead of arguments to post content. I'm thinking 200 characters. That would be less than 10% of what we allow for arguments.

As for everything else, they should be just like arguments (direct links, replies, editable, deletable, reportable, upvotes, downvotes etc etc). However, visually, they would need to be distinct, either by colour (I like the blue, suggested by Kevin) or placement or both.

Ideally, the main statement / title of the POI would always default to "Point of Information". So the user can only enter the content of the POI. Also, ideally, in the body section, where we currently ask "Explain and  prove your statement here...", we would say something like: "Enter your question, remark or information reference here..."

However, that brings us to an issue with entering POIs. When user starts entering, the platform doesn't know, if it's going to be pro, con or POI. So it still allows you to enter 2048 characters and a title and asks for statement, explanation and evidence. I don't have a good solution to this. We could of course let the user enter what they wish to enter and then when they choose to post as a POI we simply replace the statement with "Point of Information" and truncate body text to 200 characters, but that would be rather abrupt. Any better ideas, anyone? @kevincrepin @ilmartyrk @tiblu @anettlinno

**Comment by tiblu** [comment]
> However, that brings us to an issue with entering POIs. When user starts entering, the platform doesn't know, if it's going to be pro, con or POI. So it still allows you to enter 2048 characters and a title and asks for statement, explanation and evidence. I don't have a good solution to this. We could of course let the user enter what they wish to enter and then when they choose to post as a POI we simply replace the statement with "Point of Information" and truncate body text to 200 characters, but that would be rather abrupt. Any better ideas, anyone? @kevincrepin @ilmartyrk @tiblu @anettlinno

Thinking out loud. Some ideas:

1. Somehow in User friendly way make the post type selection first and then actually allow User enter the content, which would allow us to set the limits correctly.
2. In case User enters 200+ and then chooses POI, we would notify about new limit AND inform WHY this limit applies. 
3. ....

When it comes to 200 limit for the POI, if you post a link reference and add some contect, I FEEL LIKE it will easily be more than 200 characters. Not sure what the right limit is, BUT a few examples:

* Wiki links, depend on the article title and subtitle - https://en.wikipedia.org/wiki/Estonia#Economy - 45 characters
* Random ERR.ee news article link, depends on the title length -  https://www.err.ee/1608332957/usa-ja-el-hakkavad-tehnoloogiaregulatsioone-kooskolastama - 87 characters
* Random Washington Post link, depends on the title length - https://www.washingtonpost.com/world/asia_pacific/china-crackdown-tech-celebrities-xi/2021/09/09/b4c2409c-0c66-11ec-a7c8-61bb7b3bf628_story.html - 144
* Random Reuters link, depends on title length - https://www.reuters.com/technology/paid-influencers-must-label-posts-ads-german-court-rules-2021-09-09/ - 103
* Random Business Insider link, depends on the title length - https://www.businessinsider.com/theranos-founder-ceo-elizabeth-holmes-life-story-bio-2018-4 - 91

MAYBE we could exclude links from the character count? I know, there is a risk of people posting some gibberish looking like links, but not sure thats going to help them as the links are harder to read and people will skip?

I think one thing is for sure - we need to be very good at explaining Users what "Point of Information" is and what is it's intended use. It's the first time I hear about it. But I do find it a great idea to use.

**Comment by loorm** [comment]
I'm fine with excluding links from character count. Twitter data confirms, that longer is better (see source below). Twitter allows up to 280 characters per tweet **including** links. However, the average tweet is 140 characters. While I don't think a reasonable debate via Twitter is possible, for POI it's the perfect tool. POI are supposed to be these brief, concise points within the context of a longer debate. Source: https://kurtgessler.medium.com/twitter-length-study-do-longer-tweets-drive-more-engagement-and-referral-traffic-3dd0781363ff

Any other ideas how to solve the input issue? Asking beforehand or cutting it short are both a little bit "in your face". 

The point about explaining what POI are is an excellent point. We don't even need to call them POI, if someone comes up with a better name (excluding "comment" :) )

**Comment by ilmartyrk** [comment]
As we use markdown, we can possibly take advantage of adding a link functionality. User can insert shorter text eg. "Look at our [app](https://app.citizenos.com)" and we can exclude the actual link from character count. But on the API side it needs further thinking, 

I believe we can also add a warning popup when user inserts long text as an argument and then changes the type to POI, something like:

"You are changing the type of argument to POI, but your current text is x characters longer than allowed, extra characters will be removed."

"Do you wish to continue?"
Yes    No 

But just to clarify the displaying part. @loorm @kevincrepin. If we display them in the same list as arguments. Currently Pro is aligned left, Con is right. Should these POI items then be centered to make them visually more distinguishable?

**Comment by anettlinno** [comment]
I like the idea that before participating, user has to decide what she is going to post (an argument, question or else) -- it will help her configure to the message before posting it. Design-wise I would prefer if all options would be visible before making this decision and that we would not ask user to make an extra click to find them under dropdown button.  

What are the things that are being posted and how to name them? 
**Arguments**: "Add pro argument" "Add con argument"
**Points and ideas** (in idea gathering people mostly post ideas and this is where they want to post neutral "comments"): "Add an idea" / "Make a point" (these could be under one button but it would go too long probably) 
**Questions:** "Ask a question" (in my mind the indications if question is being answered or not is not necessary)

_Re to Margo: Also, ideally, in the body section, where we currently ask "Explain and prove your statement here...", we would say something like: "Enter your question, remark or information reference here..."_
Regarding the length of questions and points -- I agree that these should be short but do **we** need to limit those with certain amount of characters? Maybe we could guide users in the body section with friendly reminder that "Make your point shortly... " and "Ask one question at the time..."

**Comment by ilmartyrk** [comment]
@anettlinno I believe that forcing hard limits is better, as it really forces users to get to the point. Its easier to force a limit to "train" behaviour and then possibly remove/alter limit later than to let loose and then try to tighten rules if things get out of hand.
I do see that making the argument / POI inserting flow  Choose type -> then display form with limits can possibly resolve the issue of cutting down texts.

**Comment by loorm** [comment]
OK, so emerging consesus seems to prefer making a choice about what your are posting, then entering the post. It works. I would have hoped to find something more elegant, but perhaps this is the best solution.

I would impose limits. We have limits for arguments, too. And in spoken debates, POIs are also time-limited to 15 seconds for the same reasons Ilmar described in the previous comment.

There is going to be a separate ideation feature sometimes in the future. So I wouldn't burden POIs with the additional function of ideation (although users may, of course, use them in this manner). POI is a short, possibly neutral interjection in a debate or discussion, intended to raise a question, provide additional information / link or point out a single issue. I think adding one additional field covers it, we don't need two or three similar short-text entry fields.

**Comment by anettlinno** [comment]
> @anettlinno I believe that forcing hard limits is better, as it really forces users to get to the point. Its easier to force a limit to "train" behaviour and then possibly remove/alter limit later than to let loose and then try to tighten rules if things get out of hand.
> I do see that making the argument / POI inserting flow Choose type -> then display form with limits can possibly resolve the issue of cutting down texts.

Yes, good point, @ilmartyrk! :)

One of the options how to make it clearer for people that questions and POIs are limited is the character countdown (questions and POIs 280 characters and arguments and ideas 2048). In this case we don´t need to use warning pop-ups..

**Comment by kevincrepin** [comment]
Some suggestions how to solve this in UI: https://www.figma.com/proto/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?page-id=2%3A16032&node-id=737%3A27387&viewport=362%2C48%2C1&scaling=min-zoom

We have a comment type selector, but user can change this at any point while writing so it's not too rigid of a flow.
The selector gives extra explanation per comment type so the user understands what is expected of this comment + we immediately also show the potential character limit.

About the left/right/middle alignment situation: Middle alignment would be pretty bad for readability, so in order to not skew the perception of the other comment types being aligned left or right I would bring up the idea of left aligning everything and relying purely on the colour coding?

**Comment by loorm** [comment]
**Selector.** Works for me. 

**New category** 
I would just introduce **one** new category. Whether the user inputs a point, a reference to evidence or a question is up to the user. So 3 categories.

I like the abbreviation to "point" as opposed to "point of information" as used in debates. And then in the dropdown selector we can explain, that "Points are short interjections, intended to share evidence, ask a question or neutrally draw attention to something that has so far been missed in the debate."

**Alignment**
This is very important, since it has a great potential influence on the readability of the discussion. I'm hesitant to let go of the left-align / right align model. Maybe do a visual mockup?

**Misc.** We have character limits for arguments (visual indicates no limit). The limit is 2048 chars.

**Comment by kevincrepin** [comment]
Maybe we can differentiate with having the comments/arguments in colour blocks. Still keeping alignment for pro/con with green/red, but the "point" is more neutral in light shade of blue.
https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=1042%3A27965

**Comment by ilmartyrk** [comment]
@kevincrepin @loorm  @anettlinno I really like this solution, makes all the different blocks really clear for the user

**Comment by loorm** [comment]
Yeeez, very nice!

**Comment by anettlinno** [comment]
Yes, that looks beautiful! Thanks for the magic, @kevincrepin! :))

**Comment by loorm** [comment]
@anettlinno I propose to move this to Triage. I've removed my own assignment from here. This was the last issue that I was "driving". Because it's such a big change and visible change, it probably requires some explanation to the users, too @liinaguiter.

**Comment by anettlinno** [comment]
Triage 47. Est. dev. time 3 days. Sending to development.

**Comment by KatiVellak** [comment]
Very nice solution, indeed. Legal review done, no impact detected.

**Comment by ilmartyrk** [comment]
Development tasks:
- [ ] Update view
- [ ] Add new category to API
- [ ] Related issue https://github.com/citizenos/citizenos-fe/issues/796

Administrative tasks:

- [ ] Update CHANGELOG files
- [ ] Inform marketing of new feature(s)
- [ ] Inform localization on new translations

**Comment by tiblu** [comment]
### TODO

**API:**
- [x] Add `Comment.type` `poi` (point of idea, point of information)
    - [x] Model
    - [x] DB migration - add `poi` after `con` - https://www.postgresql.org/docs/10/sql-altertype.html
- [x] `POST /api/users/:userId/topics/:topicId/comments` - save a comment with type `poi`
     - [x] Argument type specific limits PRO/CON - 2048, POI - 500 
- [x]  Comment listing API-s to return with type `poi`
    - [x] `GET /api/users/:userId/topics/:topicId/comments` & `GET /api/topics/:topicId/comments` 
     
**FE:**

- [x] Update existing visuals
    - [x] Colored background for different types of arguments
    - [x] Gray thumbs up/down buttons  
    - [x] TBD...
- [x] Add an argument form
    - [x] MVP
    - [x] Final designs
- [x] Edit an argument form 
    - [x] MVP
    - [x] Final designs
    - [x] Translate errors
        - [x] `MSG_ERROR_PUT_API_USERS_TOPICS_COMMENTS_40000_SUBJECT` - too short or too long subject - "Subject can be 1 to 128 characters long. *"  **NO NEED - UX denies from submitting form**
        - [x] `MSG_ERROR_PUT_API_USERS_TOPICS_COMMENTS_40000_TEXT` - too short or too long comment text - "Text can be 1 to 2048 characters long. *" **NO NEED - UX denies from submitting form**
     - [x] Switching from POI to PRO/CON does not allow typing more characters. Visually character counter is updated, but old `maxlength` applies to the textarea.
- [x] Edit reply    
- [x] Fix "Read more" layout
- [x] Fix the argument type "not selected" text to be gray, not black. 
- [x] Argument type specific limits PRO/CON - 2048, POI - 500
    - [x] FE
        - [x] MD editor does not properly limit based on type - if I change to POI, the textarea maxlength is not applied, remains to be the initial (2048). Character count IS updated correctly, counting to negative values. 
        - [x] MD editor textarea does NOT have red borders on input error
        - [x] Make the whole `dropdown_item` element clickable. Right now only text is, if you missclick text, it closes the dropdown without selection.
        - [x] POI length limit reached shows invalid maximum character count 2048 instead of 500. API returns correctly.
        - [x] MD - fix line spacing for MD text, specially for lists.
        - [x] MD editor textarea does NOT trigger `ng-keyup`, that is "on-the-fly" error checking does not work for the argument text. We MAY not need it, but was there before the MD.  **DONE:** MD editor does not allow you to exceed limit anyway, thus on the fly checking does not make sense any more. We used to alllow User to type as much as they wanted but show error, now we just limit typing. So removing all `ng-keyup` triggers where MD is used.
        - [x] Usage of `translate-compile` inside template. Is that really needed? - **DONE:** It is, otherwise "log-in" links will not work.
    - [x] API

**Comment by tiblu** [comment]
### Released 17.12.2021

**Implementation notes: **

* The UX is NOT as defined in Figma, but a mid-way solution. Reasons:
    * Did alot of refactoring and helped out the UI, wanted to release the big patch so that there would be less troubles with merge when other people do something.
    * IT MAY take a while to implement the complete UX. I am afraid mobile needs a different one.

![image](https://user-images.githubusercontent.com/7405383/146560368-9e8ce877-58d5-4f21-8491-e9b15f0346dd.png)

**Comment by anettlinno** [comment]
Tested. Mid-way solution works nicely.

**Comment by seppviljar** [comment]
Suggestion: if you want 3-letter counter label in top, I'd suggest using "inf". Current "poi" is rather debate-specific term, isn't it (I had to google) and doesn't work lowercase, I'm afraid? :)

Also, what about "Make a point/Ask for info" for dropdown?

**Comment by anettlinno** [comment]
> Suggestion: if you want 3-letter counter label in top, I'd suggest using "inf". Current "poi" is rather debate-specific term, isn't it (I had to google) and doesn't work lowercase, I'm afraid? :)
> 
> Also, what about "Make a point/Ask for info" for dropdown?

I personally think it´s great that we follow debating vocabulary :) It is well proved and our aim is to gently guide people to use argumentation in their discussions. "Poi" for "point" is understandable to me. 
"Make a point/Ask for info" is too long for mobile? I would then suggest "Make a point/question" (although "make a question" sounds weird :) )

**Comment by tiblu** [comment]
@anettlinno There are references in this item for different character limits for different argument types. Are we planning to have different limits or not? And if so, what are the limits for different types? Right now we have generic 2048 character limit for pro and con arguments.

**Comment by anettlinno** [comment]
> @anettlinno There are references in this item for different character limits for different argument types. Are we planning to have different limits or not? And if so, what are the limits for different types? Right now we have generic 2048 character limit for pro and con arguments.

@tiblu if to think about what is the aim of POIs (make a statement or ask a question or clarity) then I think we want to keep them rather short. I´m not sure how confusing this is for "regular" user, but I think it´s worth trying if we want to keep the debating format in our argumentary. As characters are being showed and count-downed in the lower right corner, then this helps users. 
I tested with different amounts of characters and to make a brief point then I think 500 characters should be enough. Open for any other suggestion though.

**Comment by tiblu** [comment]
> > @anettlinno There are references in this item for different character limits for different argument types. Are we planning to have different limits or not? And if so, what are the limits for different types? Right now we have generic 2048 character limit for pro and con arguments.
> 
> @tiblu if to think about what is the aim of POIs (make a statement or ask a question or clarity) then I think we want to keep them rather short. I´m not sure how confusing this is for "regular" user, but I think it´s worth trying if we want to keep the debating format in our argumentary. As characters are being showed and count-downed in the lower right corner, then this helps users. I tested with different amounts of characters and to make a brief point then I think 500 characters should be enough. Open for any other suggestion though.

Thanks for the quick reply! 

I'm on the side of not adding different restrictions until we see the need for them. In general doing work that MAY be needed, but not sure if it is.

**Comment by tiblu** [comment]
@anettlinno 

![image](https://user-images.githubusercontent.com/7405383/146788391-7a9ec263-570a-4273-983d-ee2ef902365f.png)

I was unable to find descriptions for the different argument types in the new dropdown. Did I miss them or they do not exist?

**Comment by loorm** [comment]
> I'm on the side of not adding different restrictions until we see the need for them. In general doing work that MAY be needed, but not sure if it is.

Since we restrict arguments to 2048 characters, not limiting POIs would be inconsistent. I support limiting to 500 chars.

On the human communication scale, where at one end we have emergency radio communications (extremely brief, super defined and repeated back) and at the other end we have coffee table chatter (extremely verbose, non-structured), argumentation is not in the middle, it is tilted towards the radio comms end of the spectrum. Therefore, in a good argument-based discussion or debate, there are always limits to communication, to prevent excessive verbosity. In verbal encounters, these limits are imposed via time (both sides have 5 minutes per speech), in written systems it should be imposed via char limits (and possibly posting limits). Uncontrolled verbosity is counter-productive. When people work with limits, they consider what they say more carefully, improving clarity and structure. I recently posted a comment on aeon.co and was informed, that I am allowed 1 comment per day. Again, the limit makes you consider what you type much more than having unrestricted access.

I support limiting to 500 chars.

**Comment by tiblu** [comment]
@loorm @anettlinno @ilmartyrk 
> > I'm on the side of not adding different restrictions until we see the need for them. In general doing work that MAY be needed, but not sure if it is.
> 
> Since we restrict arguments to 2048 characters, not limiting POIs would be inconsistent. I support limiting to 500 chars.
> 
> On the human communication scale, where at one end we have emergency radio communications (extremely brief, super defined and repeated back) and at the other end we have coffee table chatter (extremely verbose, non-structured), argumentation is not in the middle, it is tilted towards the radio comms end of the spectrum. Therefore, in a good argument-based discussion or debate, there are always limits to communication, to prevent excessive verbosity. In verbal encounters, these limits are imposed via time (both sides have 5 minutes per speech), in written systems it should be imposed via char limits (and possibly posting limits). Uncontrolled verbosity is counter-productive. When people work with limits, they consider what they say more carefully, improving clarity and structure. I recently posted a comment on aeon.co and was informed, that I am allowed 1 comment per day. Again, the limit makes you consider what you type much more than having unrestricted access.
> 
> I support limiting to 500 chars.

I am not proposing having no limits. I am proposing the limit to be the same for all argument types - 2048.
I understand the thought process around hard limits, but if someone wants to go over the limits, they will add several arguments. 
I FEEL like the implementing different limits for different types will add extra work and not much value. Extra work meaning approx 3-6hrs of dev time.

**Comment by anettlinno** [comment]
@tiblu I think there are no argument type descriptions and here is what I propose. @loorm and @seppviljar please check and make suggestions where needed :) 

**Add a pro argument**. Use this option if you agree and want to leave an argument that is supportive or in favor of the topic. 
**Add a con argument**.  Use this option if you disagree and want to leave an argument that does not support the topic. 
**Make a point**. Use this option if you want to make a short statement or a point, ask a question or clarity about the topic. 

@tiblu as @ilmartyrk pointed out then it´s always easier to soften the restrictions if we see that these does not make sense rather then start softly and then strengthen the rules. I think Margo explained very well the principles of what kind of points we want people to make -- short, precise and purposeful. This is how we can softly guide our users to thoroughly think through how and what they express. I think those 3-6 hours of dev time are well spent if we´ll do this enhancement :)

**Comment by tiblu** [comment]
> @tiblu I think there are no argument type descriptions and here is what I propose. @loorm and @seppviljar please check and make suggestions where needed :)
> 
> **Add a pro argument**. Use this option if you agree and want to leave an argument that is supportive or in favor of the topic. **Add a con argument**. Use this option if you disagree and want to leave an argument that does not support the topic. **Make a point**. Use this option if you want to make a short statement or a point, ask a question or clarity about the topic.
> 
> @tiblu as @ilmartyrk pointed out then it´s always easier to soften the restrictions if we see that these does not make sense rather then start softly and then strengthen the rules. I think Margo explained very well the principles of what kind of points we want people to make -- short, precise and purposeful. This is how we can softly guide our users to thoroughly think through how and what they express. I think those 3-6 hours of dev time are well spent if we´ll do this enhancement :)

Thanks for the descriptions. 
@loorm arguments are based on understanding that I wanted to remove limits which is not true. I did not want different limits for different types of arguments. I understand the need for keeping conversations (arguments) short in general. I do not see how there is a need specific case for POI. Don't see how 500 makes a big difference vs 2048 noted that I can always continue where I left off with another argument be it poi/con/pro. 
BUT, that said, I have not done any debating, thus by the end of the day I trust your call. This is all a "gut feeling".

**Comment by loorm** [comment]
> I did not want different limits for different types of arguments. I understand the need for keeping conversations (arguments) short in general. I do not see how there is a need specific case for POI. Don't see how 500 makes a big difference vs 2048 noted that I can always continue where I left off with another argument be it poi/con/pro.
> BUT, that said, I have not done any debating, thus by the end of the day I trust your call. This is all a "gut feeling".

OK, I see, you proposed having 2048 char limit for all input types. I bring two examples in support of shorter char limit.

1. In common verbal debates (political, TV etc), there are often things called "remarks" - short points or questions that can be made in response or in reaction to someone's statement. These are always time limited and always shorter than the main statements.
2. In all competitive debate formats, that use POIs, time limits for POIs are considerably shorter than for constructive speeches. In BP format, for instance, speeches are 5 or 8 minutes long, while a POI is limited to 15 seconds. These time limits exist so that noone would abuse POIs to start constructing their own arguments. In other words, time limits help keep POIs what they are supposed to be - short interjections.

On the strength of these two examples, I support a shorter character limit for POIs. Writing this, I'm thinking perhaps even 500 chars is too long. Perhaps it should be 200, making it 10% of argument length.

As @tiblu pointed out, right now, you can simply make another POI, if you run into the limit and continue where you left off. In verbal debate formats, this is not allowed. You can only make one POI at a time. Then some time must pass, before you are allowed to make another point. Thus, ideally, we would have two additional rules for keeping debates and discussions orderly:

- allowing everyone to post only one POI per topic in 24 h

- not allowing the first thing in the discussion to be a POI. POIs only become available as an input type after at least one argument has been posted. 

I'm not saying, that we need to implement this right now, but I would suggest we consider these additional limitations.

**However, I strongly remain in support of a smaller char limit for POIs.** Currently, POI and argument limits are the same.

**Comment by tiblu** [comment]
## Released 21.01.2022

Some of the components released partially earlier, but completed solution as of 21.01.2022.

![image](https://user-images.githubusercontent.com/7405383/150541079-787ccb93-219c-48c5-bd2d-65fc43310b2d.png)

### Implementation notes

* Needs more work on touch devices - the statement selection descriptions are shown on "hover", but touch devices have no "hover". That said, on touch devices you can still select options. @kevincrepin promised to come up with a design in the future.
* The "Post" button and character count remain on separate lines as they were. Did not put side-to-side cause on mobile they will not fit anyway.
* Time spent: 33.64 h
    * About 1/3 of the time was spent on fixing and refactoring old things out of place in FE.

**Comment by anettlinno** [comment]
Tested. Works nicely but I have minor suggestion @tiblu . 

Would it be possible that character limit will change the same time as user clicks on the argument/poi type? Currently the character limit number is by default 2048 and it changes only after User has chosen POI, moved the cursor to the text box and started writing her point. But character limit and drop-down options could be synchronized. 

![POI](https://user-images.githubusercontent.com/45175679/150545644-489cd61d-5b8f-4f05-9d5b-b753cf9cae73.png)

**Comment by tiblu** [comment]
> Tested. Works nicely but I have minor suggestion @tiblu .
> 
> Would it be possible that character limit will change the same time as user clicks on the argument/poi type? Currently the character limit number is by default 2048 and it changes only after User has chosen POI, moved the cursor to the text box and started writing her point. But character limit and drop-down options could be synchronized.
> 
> ![POI](https://user-images.githubusercontent.com/45175679/150545644-489cd61d-5b8f-4f05-9d5b-b753cf9cae73.png)

@anettlinno  Good suggestion! Not sure how I missed it, my bad.
It has been implemented.
