### ISSUE TITLE
Improve readability of the Activity Feed

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#342]
**What?**

Activity feed is very hard to read:

* Hard to distinguish between variables and static text (topic title and rest)
* There is no way to easily differentiate activities related to your User from other User activites because there is no special hilighting of your User in the activity text.

![image](https://user-images.githubusercontent.com/7405383/69167877-4ee7b380-0afe-11ea-897f-5776b1406d60.png)

Related to:

* https://github.com/citizenos/citizenos-fe/issues/341

**Comment by loorm** [comment]
Triage 16. There's a design solution for this in #256. If we implement the design from there, it will solve most of this issue. Ready to be prioritized.

**Comment by tiblu** [comment]
While fixing this, please fix https://github.com/citizenos/citizenos-fe/issues/341 also.

**Comment by tiblu** [comment]
**NOTES:**

* In some languages, like ET, the topic title is in quotes in the translation while in the source it's not quoted.
     * NOTES: If you change source (en.json) and et.json manually in the repo, Crowdin will mark it NOT  TRANSLATED in the UI. We need to manually re-approve all translations.
* On the designs, only Topic title and Group name are highlighted. User name is not.
* Comments and topic texts are in italic.

Design from #341 
![image](https://user-images.githubusercontent.com/7405383/75024244-c3d1dd00-54a1-11ea-921e-5232800da3ae.png)


**TODO**

- [x] Move hilighting to translations. All hilighted variables - at this point only topic title and group name - will be wrapped in `<em>`.
- [x] Add styles for `<em>`
- [x] Some translations are missing variable values:
    - [ ] ![image](https://user-images.githubusercontent.com/7405383/75026411-9dae3c00-54a5-11ea-93e8-e5fcc91d3dc5.png) 
![image](https://user-images.githubusercontent.com/7405383/75030958-e7028980-54ad-11ea-97ee-428a0155ee7d.png) - part of #341 - **CAUSE:** Activity is missing Topic info. We either add the info OR we hide this activity? **REMOVE:** By the result of vote in #product Slack channel on the 21st of Feb 2020, we decided to remove this event.
    - [x] ![image](https://user-images.githubusercontent.com/7405383/75026490-bc143780-54a5-11ea-9701-47fbb922c6b9.png) ![image](https://user-images.githubusercontent.com/7405383/75028598-38f4e080-54a9-11ea-9211-71449312e22c.png)
    - [x] ![image](https://user-images.githubusercontent.com/7405383/75026562-dcdc8d00-54a5-11ea-9bb9-46d1196de779.png) - part of #341 - Looks like it has been fixed in between - 
![image](https://user-images.githubusercontent.com/7405383/75029046-0c8d9400-54aa-11ea-941c-3fe6ae72949a.png)

- [x] Remo vote container download activity
     - [x] API `/downloads` not to generate activity
     - [x] Migration to delete activities from DB
- [ ] Close https://github.com/citizenos/citizenos-fe/issues/341

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working. Minor things noticed, opened as separate issues.
