### ISSUE TITLE
Group invitations - no auto-accept

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#348]
**Overview**

When User is invited to a Group, he gets added automatically.

User has the right to choose what to participate in.
This may cause issues in the future where spammers may use this do distribute their content.

**Implementation**

Same experience as for Topic invites - https://github.com/citizenos/citizenos-fe/issues/112

**Related:**

* Topic invitations - https://github.com/citizenos/citizenos-fe/issues/112

**TODO:**

- [x] API: DB model "GroupInvite" that extends "Invite". "GroupInviteUser" that extends "GroupInvite" - all this inheritance is for consistency.
- [x] API: DB migration
- [x] API: Create invites - POST /groups/groupId:/invites - auth: Group admin
- [x] API: DEPRECATE  POST /api/users/:userId/groups/:groupId/members
- [x] API: List all invites - GET /api/users/:userId/groups/:groupId/invites/users
- [x] API: Read an invite - GET /api/groups/:groupId/invites/users/:inviteId - auth: knowing the inviteId (uuidv4)
- [x] API: Delete an invite - DELETE /api/users/:userId/groups/:groupId/invites/users/:inviteI
- [x] API: Accept an invite - POST /api/users/:userId/groups/:groupId/invites/users/:inviteId/accept
- [x] API: Create invites - emails!
- [x] FE: UI routes
- [x] FE: Inivte modal template
- [x] FE: Invite modal template translations
- [x] FE: Invite flow - use invite endpoints
- [x] FE: UI to distinct invited Users from joined Users
- [x] FE: Test member list filtering functionality
- [x] FE: Member invite delete dialog
- [x] FE: Activity - new invite -
![image](https://user-images.githubusercontent.com/7405383/110317071-47f6f400-8014-11eb-9e3c-4fd30fb1f1fe.png)
![image](https://user-images.githubusercontent.com/7405383/110318638-66f68580-8016-11eb-8653-196c50ce4fa5.png)
- [x] FE: Activity - accept invite - 
![image](https://user-images.githubusercontent.com/7405383/110317128-5b09c400-8014-11eb-95a3-17e011809fe7.png)
- [x] FE: TRANSLATIONS: Error messaging
    - [x]  Deleted
    - [x]  Expired
- [x] API: TEST: Update user level when accepting invite. - NOT A VALID CASE, as creating an invite to existing Member will update level and NOT send an invite.
- [x] API: Free text field to invitation e-mail.
- [x] FE: Free text field to invitation e-mail.
- [x] API: Create invites - POST /groups/groupId:/invites - LIMIT inviteMessage to 200 chars.
- [x] API: Create invites - POST /topics/topicId:/invites - LIMIT inviteMessage to 200 chars.
- [x] FE: BUG - inviting a User collapses the members sections on /my/groups. - https://github.com/citizenos/citizenos-fe/issues/647
- [x] Navigating between `my/topics` and `my/groups` with several `openTabs` parameters will not expand details - https://github.com/citizenos/citizenos-fe/issues/646
- [x] API: REFACTOR "GroupMember" to "GroupMemberUser" - https://github.com/citizenos/citizenos-api/issues/198

**Comment by loorm** [comment]
Triage #16. ETA 40 dev hours. Copy text and visuals can be perused from issue #112.  Ready for prioritization.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.

**Comment by tiblu** [comment]
**Deploy progress**

- [x] Testing
    - [x] DB  
    - [x] API
    - [x] FE
- [x] Production
    - [x] DB  
    - [x] API
    - [x] FE

**Testing**

- [x] New invite
- [x] Accept invite NOT LOGGED IN
- [x] Accept invite LOGGED IN
- [x] Accept invite that has been deleted
- [x] Accept invite that has expired
- [x] Activity links
     - [x] Not accepted group invite activity
     - [x] Accepted group invite activity

TBF:

- [x] Invite e-mail subject missing Group.name - ![image](https://user-images.githubusercontent.com/7405383/110647919-f475d900-81c0-11eb-8822-27b6b6006db7.png)
- [x] Activity links! - ![image](https://user-images.githubusercontent.com/7405383/110654053-79172600-81c6-11eb-9549-997a83ebe38d.png)
- [x] Invited admin member deletes self results in weird error - **FIX:** Show "Leave" Group dialog instead as this is what it basically means.

**Comment by tiblu** [comment]
Done.
For some leftovers that I did not find urgent to do right now, created separate issues to be prioritized.
