### ISSUE TITLE
 Update cookie notification

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#381]
We need to update our cookie policy and it's notification so that users could opt out on cookies that are not required for running our application.
It should look something like: 
https://www.1a.ee/ or https://ico.org.uk/

We probably should go with 1a way to add data about cookie names and what are they used for to avoid future updates. 

**TODO**

- [x] ~~List all cookies, their purpose AND expiry -~~ **DONE:** https://docs.google.com/spreadsheets/d/1TCd8to_3FLQj2qfK_QaU2EzrZ5kbVF8nZyo3u5R97ag/edit?usp=sharing
- [x] Create new cookie consent:
    - [x] Granular control over used cookies, specially on/off for 3rd party cookies - that is Google Analytics 
![image](https://user-images.githubusercontent.com/7405383/79113001-96f6c380-7d88-11ea-924d-a65e1482990a.png)
- [x] ~~Create a GH issue to replace GA with some on-premise solution.~~ **DONE:** https://github.com/citizenos/citizenos-fe/issues/457
    - [x] ~~Ask input what metrics to we want to collect to help with choosing the right tools.~~ **DONE:** Posted to Slack.

**Comment by moll** [comment]
Alternatively, you could remove all tracking cookies and thereby remove the consent banners entirely. Why clutter up a site and annoy people with something every rational person will decline?

**Comment by loorm** [comment]
Triage 16. Move to preparation. @tiblu to discuss with moll.

**Comment by loorm** [comment]
Triage 16. Move to preparation. @tiblu to discuss with moll.

**Comment by tiblu** [comment]
RAA.ee is trying to get rid of Google Analytics - https://github.com/rahvaalgatus/rahvaalgatus/issues/175

**Comment by loorm** [comment]
March monthly meeting - needs a wider discussion between legal and dev.

**Comment by loorm** [comment]
Triage 19 - Margo will initiate a long term solution discussion in the Civic Hacktivist Community. Mikk and Kati will find a short term, legally correct solution based on Google Analytics.

**Comment by tiblu** [comment]
**Cookie notification Q&A**

Q: We CAN set compulsory (functional) cookies BEFORE User accepts cookie policy.
A: True.

Q: We CANNOT set analytics/tracking cookies BEFORE User accepts cookie policy.
A: True. User must be opted out from those (analytics/tracking) cookies and user itself either opts in  or stays opted out by accepting the cookies policy.

Q: We can have 1 generic cookie policy and "Accept" button, it is enough to enable analytics/tracking IF User clicks "Accept".
A: No, if user clicks accept button, then only compulsory cookies shall be automatically turned in, everything else either stays opted out or user itself turns them on.

Q: We DO NOT have to have granular cookie opt-in control panel. That is - I accept functional cookies BUT NOT tracking etc.
A: User must have the right to segregate which cookies will be opted in, except mandatory technical one - these are on always and can´t be turned off by user.

Q: IF we could do Google Analytics WITHOUT cookes, we don't need User consent.
A: NOT SURE. **TBD**

**Comment by tiblu** [comment]
@kevincrepin We need a little update to our cookie consent. We need an extra toggle/checkbox for user to opt-in to Google Analytics.

This is one of those things looks like in the wild:

![image](https://user-images.githubusercontent.com/7405383/76744442-edb6b080-677c-11ea-9304-0e891ecaacd3.png)


![image](https://user-images.githubusercontent.com/7405383/76745309-55213000-677e-11ea-8d55-077f91c98f47.png)

**Comment by moll** [comment]
My point with https://github.com/citizenos/citizenos-fe/issues/381#issuecomment-578737354 was that no rational and sane person should (and hopefully won't) ever select "Statistics" and "Marketing" cookies, hence asking for it is a waste of everyone's time. Once you forgo optional stats/marketing cookies, you've no need for consent nor the banner in the first place.

**Comment by tiblu** [comment]
@moll I do agree, no consent is better. 
I also agree that if analytics is opt-in, most of the people would not switch it on. 
I do not agree "rational or sane person should (and hopefully won't) ever select.." - analytics and metrics are used for product development, to provide a better service, in that sense some people MAY opt-in to help out development of the product they use. Analytics are NOT ONLY for tracking people and selling the data to Big Brother.
I general for product development we still need some form of analytics. I would prefer to have analytics/metrics implemented so that there are no cookies. OFC this solution would hold anonymous data which would not be shared with 3rd parties.

**Comment by moll** [comment]
>  I do not agree "rational or sane person should (and hopefully won't) ever select.." - analytics and metrics are used for product development, to provide a better service, in that sense some people MAY opt-in to help out development of the product they use. Analytics are NOT ONLY for tracking people and selling the data to Big Brother.

I'm not even claiming people should be that much worried about their data being sold. Rather that the widespread curiosity of developers and monitoring of marketers of _individuals'_ actions doesn't nor shouldn't sit well with most people. I concede that perfect visibility into every click would help design and usability, but I would also argue that the majority of those benefits could be attained by non-privacy invading methods, from anonymous events or simple usability tests. To reformulate my claim above: _if_ most people wouldn't like someone sitting over their shoulder (and I claim they don't), to be rational, they should _never_ permit analytics. True, not all analytics are or have to be pervasive, but 1) non-pervasive analytics could be collected anonymously and 2) unfortunately the untrustworthiness of the majority of websites have spoiled the pool, so there's little incentive for visitors to presume otherwise. Having said that, I'm not even convinced GDPR protects so much against real-time monitoring as it does against storing identifiable data.

> I general for product development we still need some form of analytics. I would prefer to have analytics/metrics implemented so that there are no cookies. 

If y'all accept that a negligible amount of people would ever turn analytics on, there's hardly any point in asking for it, is there?

**Comment by moll** [comment]
(Accidentally sent the comment above too quickly. I was about to add the following)

Ranting on cookie banners, I stumbled upon Keskraamatukogu's screen on https://keskraamatukogu.overdrive.com:

![Screenshot_2020-03-20 Tallinn Central Library - OverDrive](https://user-images.githubusercontent.com/156837/77194837-91cf8d00-6ad8-11ea-91c0-636c09f8fd73.png)

Do we agree that it's entirely silly to show a modal dialog if practically everyone's going to continue with the default choice that doesn't require a dialog in the first place?

**Comment by tiblu** [comment]
@moll I do agree, this kind of modals are annoying. We're in progress of figuring out the analytics and the cookie policy with Kati. Will let you know once we have our idea how to implement things, so you can have your say.

**Comment by tiblu** [comment]
Mon, 13th of Apr 2020 Citizen OS has a meeting and we'll decide what and how to do.

**Comment by KatiVellak** [comment]
> **Cookie notification Q&A**
> 
> Q: We CAN set compulsory (functional) cookies BEFORE User accepts cookie policy.
> A: True.
> 
> Q: We CANNOT set analytics/tracking cookies BEFORE User accepts cookie policy.
> A: True. User must be opted out from those (analytics/tracking) cookies and user itself either opts in or stays opted out by accepting the cookies policy.
> 
> Q: We can have 1 generic cookie policy and "Accept" button, it is enough to enable analytics/tracking IF User clicks "Accept".
> A: No, if user clicks accept button, then only compulsory cookies shall be automatically turned in, everything else either stays opted out or user itself turns them on.
> 
> Q: We DO NOT have to have granular cookie opt-in control panel. That is - I accept functional cookies BUT NOT tracking etc.
> A: User must have the right to segregate which cookies will be opted in, except mandatory technical one - these are on always and can´t be turned off by user.
> 
> Q: IF we could do Google Analytics WITHOUT cookes, we don't need User consent.
> A:  French data protection authority CNIL has noted in their 4 July 2019 guidelines on cookies and other online trackers that analytics tools that are set up only for data collection by an organization (and not shared in any way with third parties) can be installed without consent. Other countries DPAs (ICO, DSK, AEPD, AKI) have taken the approach that the requirement for consent also applies to analytical tools if the third party uses the data, as in the typical case of Google Analytics, as well as more detailed information about the behavior of the website visitors such as keyboard entries, mouse clicks or swiping movements. In summary they are all saying the same thing, just from different angle.

**Comment by tiblu** [comment]
In-progress privacy control center proposal - https://docs.google.com/presentation/d/1karv8YsULK_R_BOZ5PGd4Iu8UaBccHnEq3q2y7Qjx0o/edit?usp=sharing.

Also related, proposal to get rid of Google  Analytics - https://github.com/citizenos/citizenos-fe/issues/457

**Comment by tiblu** [comment]
![image](https://user-images.githubusercontent.com/7405383/79775388-d602b700-833c-11ea-9838-291247d98b3a.png)


@kevincrepin @KatiVellak Created a new cookie notification proposal - https://docs.google.com/presentation/d/1ojFTLQtX_hQJy2GcxmdIjNKJFuXuozmFZchaw6dd8Lc/edit?usp=sharing
**This is the draft to show what information has to be present, UX is up to @kevincrepin. Copy texts are subject to change.**

Implementation details:

* The name of this is "Cookie notice".
* Both landing page (https://citizenos.com) AND app (https://app.citizenos.com) use the SAME cookie notice.
    * EXCEPTION: https://citizenos.com/legal/privacy/ - will NOT display cookie notice, analytics MUST be disabled UNLESS User setting to enable analytics has been set.
   * That is, IF a User saves cookie notification settings in the app (https://app.citizenos.com), then visiting landing page (https://citizenos.com) respects these same preferences and vice versa. 
* Website is NOT usable UNLESS User has set cookie preferences, NO closing from the corner or clicking on the background.
* There are 2 categories of cookies:
    * "Necessary cookies"
    * "Anonymised analytics cookies"
* ONLY "Anonymised analytics cookies" category can be optional. It can be toggled ON/OFF. DEFAULT is OFF, which means analytics are disabled, Google Analytics script is not loaded.
* Every category has "View details" (or similar) along with the overall description. "View details" displays detailed info on each cookie and it's purpose WITHOUT NAVIGATION.  The details are on slides 2-3, the number of cookies in the table MAY change. 
* The "Cookie notice" has ALWAYS a link to Privacy Policy visible - https://citizenos.com/legal/privacy/
* The "Cookie notice" CAN ONLY BE CLOSED by 2 action buttons:
    * "Enable all cookies" - Enables all cookies, including "Anonymous analytics" and saves settings and closes the "Cookie notice".
    * "Save settings" - Saves settings currently set by User. Settings === toggle states of all the cookie categories of which only "Anonymous analytics" can be changed.
* Cookie to store User settings shall be `cookie_control`, expires in 6 months, HTTPOnly - false.

Sources:

*  https://ico.org.uk/global/cookies/ - good text, weird implementation when it comes to not being able to read full cookie usage before setting cookie preferences.

**Comment by KatiVellak** [comment]
@tiblu @kevincrepin I am good to go, everything we discussed with Mikk is as should.

**Comment by kevincrepin** [comment]
Added on Invision. 
Regular dialog: https://projects.invisionapp.com/d/main#/console/9829159/414643716/preview
Dialog with expanded cookie explanation: https://projects.invisionapp.com/d/main#/console/9829159/414643717/preview

**Comment by tiblu** [comment]
@kevincrepin On mobile it acts like a regular modal right? (100% width..)

@KatiVellak How does it look?

![image](https://user-images.githubusercontent.com/7405383/79981744-dcfd0700-84ad-11ea-9292-9de533348fea.png)

![image](https://user-images.githubusercontent.com/7405383/79981797-f3a35e00-84ad-11ea-80df-9e0389371f4c.png)

**Comment by KatiVellak** [comment]
@tiblu @kevincrepin the buttons "Enable all cookies" should have same blue background color as "Save settings" button has. They should look the same. but other than that it looks good and I have nothing to add or change 👍

**Comment by tiblu** [comment]
TODO:

- [x] Modal visuals
- [x] Controller to set the `cookie_control` cookie
- [x] Set analytics ONLY if `cookie_control` allows.
- [x] Localization
- [x] View details/ Close details toggle

Testing checklist:

- [x] Modal opens no matter the page state IF `cookie_control` cookie has NOT been set.
- [x] Modal cannot be closed any other way but choosing one of the actions
- [x] Modal privacy control link takes to "Privacy and Cookies Policy"
- [x] "Save settings" saves current state of UI  respecting the "Analytics" toggle.
- [x] "Enable all" enables "Analytics" and saves current state.
- [x] `cookie_control` cookie is set correctly.
- [x] UI respects the no-analytics option. Does not load analytics script, does not report analytics.
- [x] Any translation keys missing?
- [x] Old cookie notification is NOT shown.
- [x] Looks as good on mobile
    - [x] BUG 
![image](https://user-images.githubusercontent.com/7405383/81169812-2c5d3000-8fa2-11ea-91ec-920ae2d9c14e.png)

**Comment by tiblu** [comment]
Live release BLOCKED - @oksks discovered that there is no way to change language when cookie control is open. 
Waiting for decision on how to solve this. Conversation in Slack.

**Comment by tiblu** [comment]
Done, live. Ongoing discussion on the localization of the text tho.

**Comment by tiblu** [comment]
![image](https://user-images.githubusercontent.com/7405383/81602678-b60f6200-93d5-11ea-9ac3-ac44c4e3f494.png)

**Comment by moll** [comment]
The [updated European Data Protection Board guidelines](https://edpb.europa.eu/sites/edpb/files/files/file1/edpb_guidelines_202005_consent_en.pdf) are relevant for CitizenOS's cookie popover implementation. They've clarified that cookie walls, i.e preventing use of the site without interacting with the cookie popover, isn't acceptable:

> 40. Example 6a: A website provider puts into place a script that will block content from being visible except for a request to accept cookies and the information about which cookies are being set and for what purposes data will be processed. There is no possibility to access the content without clicking on the “Accept cookies” button. Since the data subject is not presented with a genuine choice, its consent is not freely given.

Via the hypocritical TechCrunch, which too is non-compliant with its cookie wall: https://techcrunch.com/2020/05/06/no-cookie-consent-walls-and-no-scrolling-isnt-consent-says-eu-data-protection-body/

**Comment by tiblu** [comment]
> 1. nt from being visible except for a request to accept cookies and the information about which cookies are being set and for what purposes data will be processed. There is no possibility to access the content without clicking on the “Accept cookies” button. Since the data subject is not presented with a genuine choice, its consent is not freely given.

Thanks @moll for providing the info.
AFAIK, we do not have a cookie wall in a sense that you CAN continue using the site without accepting all cookies. 
BUT, I'm not an expert, thus I kindly asked @KatiVellak to look at this.

**Comment by moll** [comment]
The marketing site indeed doesn't prevent browsing without interacting with the cookie banner, but the app's site (https://app.citizenos.com) sure does.

The way I read the above paragraph is that it's about even *accepting* the defaults, not about accepting *all cookies*. That seems to match TechCrunch's reading, too. Given the need for analytics cookies to be opt-in is already well-covered elsewhere, I think it's fair to presume the guideline's example above is truly about a cookie wall forcing explicit acceptance of functional cookies. That's the cookie wall the Internet Advertising Bureau Europe also utilized, which they've since changed:

> As we noted in our report on the Dutch clarification last year, the Internet Advertising Bureau Europe was operating a full cookie wall — instructing visitors to ‘agree’ to its data processing terms if they wished to view the content.
>
> The problem that we pointed out is that that wasn’t a free choice. Yet EU law requires a free choice for consent to be legally valid. So it’s interesting to note the IAB Europe has, at some point since, updated its cookie consent implementation — removing the cookie wall and offering a fairly clear (if nudged) choice to visitors to either accept or deny cookies for “aggregated statistics”…

Given that functional cookies don't need accepting in the first place, this makes sense. The cookie wall is pure annoyance, provides no value, eliminates actual choice and fortunately seems to be GDPR non-compliant. While on the topic, it seems Cloudflare's also putting their `__cfduid` cookie on the first visit to https://app.citizenos.com, further undermining the reason for pestering visitors in the first place. If CitizenOS is already storing functional cookies, what's the point of asking after the fact. ;)

**Comment by oksks** [comment]
I agree with @moll, that our app currently is behind a cookie wall - there's absolutely nothing you can click/scroll to, unless you click one of these:
- "Save Settings" (to be honest, I'm not sure what this button does, as it seems you can only disable the "analytics cookies", not the "necessary cookies" before clicking that - what settings am I saving + is there no way for me to reject all this?), or 
- "Enable All Cookies"

Btw @tiblu here's how it looks on the mobile - I'm afraid it doesn't look like a Citizen OS page and the only mention of "Citizen OS" in the header is hidden (for example, in Russian and German). 
We should definitely at least wrap the text in the header and maybe add a logo there, too, so it doesn't look like our site is hijacked (which it does, if you don't understand the language the text is in):

![Screenshot_20200513-153231_Chrome](https://user-images.githubusercontent.com/34126353/81987247-f07d3700-9641-11ea-8388-cb6c4df85c05.jpg)

**Comment by KatiVellak** [comment]
@moll @oksks @tiblu 
EDPB guidelines are in line with the decision of the Court of Justice of the European Union in the case of Planet 49 and recent EU data protection authorities’ guidelines (AEPD (Spanish data protection authority) Guide on the Use of Cookies, CNIL (French DPA) new guidelines on cookies and other online trackers, DSK (German Data Protection Conference) guidelines, ICO (UK´s Information Commissioner´s Office) updated guidance on the use of cookies and similar technologies) on cookie consent which been in detail analysed by me before suggesting and working on the solution we have in place now. 
The „data for access“ model (mechanisms which prevent users who do not accept the use of cookies from accessing a website or mobile app) that requires the user to “accept” tracking cookies to access the websiteʼs or appʼs content is something EDPB and those guidelines I have referred above (published before EDPB guidelines already) states is not correct to use. Thus, demanding consent as the price for getting onto the website (the cookie wall), is not considered as valid consent, since the user is forced to accept cookies to access the website. The user is thereby not presented with a genuine choice and consent is not freely given.
The above is exactly what and how @moll made an example of IAB Europe handling the cookies. Unfortunately, it seems that now they are still non-compliant with the cookies and consent requirements, because they have no notification about using Google Analytics nor asking my consent about such use, but according to their PP they make use of it. Not only I´ve been left without my free choice, there is even no transparency of the use of it. The short summary of Planet 49 should explain it well: Websites must ask for cookie consent for all cookies other than cookies that are technically required to operate the website or to provide the website service to the user. In other words, tracking, marketing and analytics cookies may only be used with explicit, clear, informed (art 13 GDPR) and prior consent, for example, via a consent management tool. The purpose of this is to protect interference with a users' 'private sphere'. This 'private sphere' includes any information (regardless of whether the information stored or accessed is personal or not) stored on a users' device, whether personal or otherwise, so as 'to protect users from the risk that hidden identifiers' enter their device without their knowledge.

Citizen OS cookie notice does give you the access to the website even in case you only agree to use necessary cookies. Moreover, Citizen OS cookie preferences are by default set only to use necessary cookies and user must him/herself opt-in to analytical cookies. This does not constitute a cookie wall, because user has genuine choice to freely decide which cookies are in and out. User must give it´s active consent to track the user with cookies, the requested information is provided through detailed information and user is offered the possibility to object to the use of cookies or allow the user to decide which cookies he/she consents (granularly).

**Comment by moll** [comment]
Thanks for the input!

As a reminder to myself, there are two different cookie forms involved on CitizenOS's sites — the cookie banner on https://citizenos.com and the modal dialog (what I'd still call a "wall") on https://app.citizenos.com/en.

> Citizen OS cookie notice does give you the access to the website even in case you only agree to use necessary cookies.
> Websites must ask for cookie consent for all cookies other than cookies that are technically required to operate the website or to provide the website service to the user.

Given that necessary cookies are set implicitly (and some even before the cookie form is shown), I'd say the term "agree to necessary cookies" isn't really accurate. As one can't _not agree_ to necessary cookies,  "agree" there isn't consent and effectively becomes "hide popup".

_If_ the only **illegal** cookie wall is one that prevents further browsing without accepting unnecessary cookies, I guess the choice between a banner and a modal dialog comes down to design. Why would one choose a modal dialog given they've been known to be user-hostile since we first got ads on the web, is beyond me, but at least by your reading they're not illegal. I do wonder why Citizen decided to go with a banner on the marketing site, but a modal dialog on the app, though.
