### ISSUE TITLE
Etherpad - inline vote - UX improvements

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#398]
**What is the problem?**

Inline voting suffers from small bugs that distract user and do not offer good user experience.

![image](https://user-images.githubusercontent.com/7405383/77053964-cb6c9f00-69d7-11ea-8ee6-ca04a89e7d4a.png)

![image](https://user-images.githubusercontent.com/7405383/77053916-bc85ec80-69d7-11ea-9300-6b54a90ae62c.png)

**TODO:**

- [x] Add an icon to the end of the line containing inline vote. Same implementation as for inline comment.
- [x] Vote creator user name is missing (null).
- [x] Vote description text should be black when the input has been edited.
- [x] Inline vote should be highlighted as green - https://projects.invisionapp.com/d/main#/console/9829159/301183006/preview
- [x] The "arrow" pointing to the vote that's been opened should be positioned correctly - back, front, below or anywhere not to overlap the text.

**Comment by loorm** [comment]
Triage 17: @kevincrepin - we had a look at the views in InVision. We did not find an icon for in-line voting. Can you please create these icons or otherwise propose a solution?

**Comment by kevincrepin** [comment]
The idea was to highlight in green: https://projects.invisionapp.com/d/main#/console/17224475/362147247/preview 

We can also add the additional "speech bubble" in green to indicate something happening?

**Comment by tiblu** [comment]
> The idea was to highlight in green: https://projects.invisionapp.com/d/main#/console/17224475/362147247/preview
> 
> We can also add the additional "speech bubble" in green to indicate something happening?

@kevincrepin This link is not working any more, but I think you were thinking about https://projects.invisionapp.com/d/main#/console/9829159/361927550/preview.
Also yes, green bubble or some other would help spot the vote and also make it consistent with inline comments.

**Comment by kevincrepin** [comment]
yes, exactly :) Nice job finding it again :D

**Comment by loorm** [comment]
This appears half-done. Assigning for Triage.

**Comment by loorm** [comment]
Triage 22. Scope is highlighting mini-voting areas in green and implementing the green icon on the right for mini-voted areas. Est dev time 24 hours. Prioritizing.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by ilmartyrk** [comment]
@kevincrepin  what Icons should I use? I have added the functionality to have icons at the ends of the lines too, but I am not sure what icons to use. I believe it should be inline with other EP designs but probably not my call to make
 t

**Comment by kevincrepin** [comment]
Think we agreed on having the same speech bubble as with the inline commenting, but make it green. I guess the number can be the total amount of votes?

But not sure in the long run if these additional bubble indications are scalable. imagine having many of them, it's going to get messy. I'd rather go only for different colour highlighting but that's not very accessible (contrast, colour-blindness etc)...

Also checking now, the highlights only show in edit mode?

I've attached an svg of the bubble, so we can play with the idea.
[topic_highlight_indication.svg.zip](https://github.com/citizenos/citizenos-fe/files/5026953/topic_highlight_indication.svg.zip)

**Comment by BeccaMelhuish** [comment]
Hello, I've been making screenshots of different features in action for Marketing purposes, and found a bug in this one which I thought I would add here? (I can also make a separate issue if preferable). 

It seems that the mini-vote box will only appear if I have not made any changes to the text as a whole. However if I have made any edits, even just adding a space to the end of the full text (or any words/ a new paragraph below), then when I click on the greyed out words the mini-vote box will not appear - nothing happens. For example, in this screenshot below, when I pasted the full text, then created the mini-vote all worked fine, but as soon as I added the space at the very end of the paragraph, the mini-vote box no longer appears when clicked. (I tried this with several sentences and editing the topic text after having created the mini-vote definitely seems to be the issue). If I went out of the topic and came back in though, it did appear fine when clicked, even on the edited text. 

![image](https://user-images.githubusercontent.com/61320526/89643841-8aa1f380-d8ae-11ea-8eea-4f04d8ff6203.png)

Also, just a visual issue, but when the mini-vote box does appear, it always seems to do so with the selection circle out of line with the vote option text, like this below. (The Indonesian is a separate issue that I've reported separately!). 

![image](https://user-images.githubusercontent.com/61320526/89643718-49114880-d8ae-11ea-92be-56be7f3726c3.png)

**Comment by ilmartyrk** [comment]
Thank you @BeccaMelhuish, I've made the fixes hope it works and looks better now

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Just getting back to this Marketing graphic now. Thank you, it does! But there are still some other issues it seems, it was still a bit hard to get a good screenshot on my phone, and therefore would be hard for users to use too I think. 

I'm attaching a few different screenshots which show the issues I had, which are:

- The blue dots of the selected text show through the pop-up.
- Sometimes the 'comment/create voting' black box doesn't show up when selected, sometimes it's only the usually 'copy, paste, etc. from my phone'. 
- If the text selected to vote on is near the bottom of the box, it makes both the black 'comment/create voting' box and the mini-vote pop-up box smaller (as it is cut off by the bottom of the text box), so you have to try and scroll within a tiny space to select the 'create voting' option or to fill out all the fields in the mini-vote setup box, which in the latter case is pretty fiddly/difficult to try and do. 

![Screenshot_20201015-091634](https://user-images.githubusercontent.com/61320526/96103695-4f3c2a80-0ed8-11eb-85bb-4d38ac8cdd6a.png)
![Screenshot_20201015-092003](https://user-images.githubusercontent.com/61320526/96103749-5e22dd00-0ed8-11eb-94a2-5b0f3cd3949d.png)
![Screenshot_20201015-092015](https://user-images.githubusercontent.com/61320526/96103835-7266da00-0ed8-11eb-85d3-a0f2963a7b9f.png)
![Screenshot_20201015-092034](https://user-images.githubusercontent.com/61320526/96103838-72ff7080-0ed8-11eb-86b4-6b514846ed86.png)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish there is no quick unfortunately.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk OK no worries! Will keep an eye on the issue updates :)

**Comment by loorm** [comment]
Triage 27. Unable to replicate on Android 7, Galaxy S6, for the most part.

- "The blue dots of the selected text show through the pop-up." This was successfully replicated, however, there is nothing we can do about this. This is Android specific.
- The rest of the visuals and functionality worked fine.

@BeccaMelhuish Can you please specify the phone / system you were using? Is it properly updated?

Moving back to "In preparation" until we know more about the possible bug.

**Comment by BeccaMelhuish** [comment]
Hi @loorm, I'm using a Motorola Moto G6, with Android 9. It wasn't updated, but I just updated it and I'm sorry to say it's all just the same! 

I was using Chrome, but thought I'd also try it on the Firefox browser app, but unfortunately that actually made it worse. I'll attach a few screenshots, which mostly show the same things, but the new issues I found using it in Firefox were:

- It was very difficult to get the black box with the 'comment/create voting' options to appear. Double tapping or holding my finger down on the word often didn't select it, and therefore the options box didn't pop up. (Sometimes it worked fine, but more often than not I had to really persevere a lot to try and get the word to select and the black box to appear). 
- I managed to get it to work in the end, but then initially tapping the 'create voting' didn't do anything. The create voting went paler as if selected, but no options box appeared. In future attempts it did work OK though. 
- For the comment box, it wasn't possible to scroll within the pop up box at all, so depending how close it was to the bottom of the screen it was either not possible to type a comment, or not possible to get to the blue button to submit it. 
- Also then tapping back in the text to try and get rid of the comment pop-up box deleted the word I had selected. 
- For the mini-vote pop-up, it was possible to scroll within the box even when only a narrow bit was viewable, but as you'll see in the screenshot, it wasn't possible to make it scroll down far enough to be able to read or click on the blue button to submit it. 

![Screenshot_20201021-135900](https://user-images.githubusercontent.com/61320526/96718726-b65e5100-13a8-11eb-956d-bd36f872d5f7.png)
![Screenshot_20201021-135911](https://user-images.githubusercontent.com/61320526/96718730-b78f7e00-13a8-11eb-8087-3fc0565c2b1f.png)
![Screenshot_20201021-135916](https://user-images.githubusercontent.com/61320526/96718731-b78f7e00-13a8-11eb-90ac-9947e9c6abe4.png)
![Screenshot_20201021-140005](https://user-images.githubusercontent.com/61320526/96718735-b8281480-13a8-11eb-9026-e93ab15f042e.png)
![Screenshot_20201021-140051](https://user-images.githubusercontent.com/61320526/96718736-b8281480-13a8-11eb-9a28-730c73dad74a.png)
![Screenshot_20201021-140103](https://user-images.githubusercontent.com/61320526/96718737-b8c0ab00-13a8-11eb-9d13-cb359674e64f.png)
![Screenshot_20201021-140113](https://user-images.githubusercontent.com/61320526/96718738-b8c0ab00-13a8-11eb-9e59-949e4dd61219.png)

**Comment by loorm** [comment]
Triage 41. We are still unable to replicate. We will try some more, but if we can't replicate it, we can't fix it. Timebox for 2 hours. If unreplicated, close issue.

**Comment by ilmartyrk** [comment]
I can confirm that in Firefox the editor behaviour is not as intended, worst issue is with typing and with selecting text like @BeccaMelhuish also had. Text input issue seems to be directly related with etherpad core functionality, but other issues seem to be Android related. I will close this issue for now. But I am planning on updating our Etherpad version soon, maybe it can solve some issues for us.
