### ISSUE TITLE
Switch CSP from report-only to block

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#422]
**Intro**

We had an investigation (https://github.com/citizenos/citizenos-fe/issues/399) to see if we could use CSP block instead of report-only.
The result is that there are a few things to consider/do:

**TODO**

- [x] Fix Estonian ID-card plugin - https://github.com/open-eid/chrome-token-signing/issues/158
- [x] Switch policy to "block"
- [x] Create a meaningful way of grouping and monitoring CSP violations - it ain't gonna be easy, see https://github.com/citizenos/citizenos-fe/issues/399 for details.
- [x] Observe if Users are annoyed by some plugins not working.

**Comment by loorm** [comment]
Triage 18: Mikk will sleep on it. Several pro and con arguments.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.

**Comment by loorm** [comment]
Related to https://github.com/citizenos/citizenos-api/issues/164

**Comment by ilmartyrk** [comment]
Added page.js file for signing to work  https://github.com/open-eid/chrome-token-signing/issues/158. We already have log monitoring alert asigned for CSP reports. Also updated topic sync to replace inline styles with classes.

**Comment by ilmartyrk** [comment]
We are getting alerts from logs, but haven't heard of anything not working for users so closing this issue
