### ISSUE TITLE
Chrome cookie policy changes - authentication does not work in test, MAY not work in prod in the future

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#442]
**Intro**

Chrome is enforcing new cookie policies witch has broken authentication in Citizen OS testin env.
It MAY break it in live as well.

Warning in console:
```
A cookie associated with a cross-site resource at https://citizenos-citizenos-api-test.herokuapp.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
```

**TODO:**

- [x] Read through what the change is about - https://web.dev/samesite-cookies-explained/
- [x] Make it work given the restrictions.
     - [x] Citizen OS API - `SameSite=None` due to cross domain requests in Widgets that are embedded in Iframes.
     - [x] Etherpad - probably same case - `SameSite=None` is required as the Herokuapp is in the public suffix list (https://web.dev/samesite-cookies-explained/#explicitly-state-cookie-usage-with-the-samesite-attribute). We have 2 options:
          * ~~Etherpad to start supporting `SameSite=None`~~
          * OR move Citizen OS testing env to *.citizenos domain.
![image](https://user-images.githubusercontent.com/7405383/77180147-30a4bb00-6ad2-11ea-958d-44425d1b4c50.png).

**Comment by tiblu** [comment]
### Investigation results
After reading https://web.dev/samesite-cookies-explained/ and https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-03 the conlusion is:

* When setting cookies, `SameSite: <Strict|Lax|None>` should be sent.
    * `Strict` - cookie sent only with first-party requests
    * `Lax` - cookie sent only with first-party requests AND top-level navigations (that is when a link to your site is clicked on a 3rd party site)
    * `None` - cookie is sent with every request, which is the classic/old behaviour. CANNOT BE USED without `Secure` flag.
* When not present `Lax` is default, which explains why testing env does not work - this means that cookie is sent only if it's first-party that is same doman that is URL bar shows the same domain that the cookie was set for OR the domain suffix is in public suffix list (https://web.dev/samesite-cookies-explained/#explicitly-state-cookie-usage-with-the-samesite-attribute) which is the case for *.herokuapp.com. Last rule is the cause for test env to be "cross-site".
* The idea is to protect against CSRF attacks and protect User privacy.
* WIDGETS NEED A CHECK! They MAY need `None`. **CONFIRMED:** Widgets will not work without `None`. In the future we MAY consider separate session for widgets so that widget sessions are `None` and COS own sessions are `Lax`.

**Comment by tiblu** [comment]
DONE!

All testing envs have been moved to citizenos.com subdomain:
* FE - https://test.app.citizenos.com
* API - https://test.api.citizenos.com
* Etherpad - https://test.p.citizenos.com 

Added a User notification to let know that he/she is browsing testing environment:
![image](https://user-images.githubusercontent.com/7405383/77337849-284abb00-6d32-11ea-948f-98c19cb6f45a.png)

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.
