### ISSUE TITLE
Find out what's the effort to implement multiple choice voting using the API

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#443]
### Intro

We've been thinking about multiple choice voting from the beginning of the times, but it has never been implemented. 
There seems to be growing interest in the feature.

### TODO

- [ ] Find out what's the effort of implement multiple choice voting in the API

NOTES:

* From API perspective, I think it's easiest to make an integration test that triest to do multiple choice voting and see what blows up.

Related to:

* https://github.com/citizenos/citizenos-fe/issues/413

**Comment by tiblu** [comment]
### Progress

- [x] Regular voting (`authType=regular`)
    - [x] Vote - https://github.com/citizenos/citizenos-api/commit/cb8ba6ad410009d53220e5b87bec3fa9f4f30dd3
    - [x] Re-vote - https://github.com/citizenos/citizenos-api/commit/cb8ba6ad410009d53220e5b87bec3fa9f4f30dd3
    - [x] Vote counting - https://github.com/citizenos/citizenos-api/commit/cb8ba6ad410009d53220e5b87bec3fa9f4f30dd3
    - [x] DELEGATION - vote, re-vote, vote count - **DONE:** Was bugged - https://github.com/citizenos/citizenos-api/commit/02ff2122325c6dfb0f6b5ef2279871bc67938c1a
- [x] Hard auth voting (`authType=regular`)
    - [x] Vote - https://github.com/citizenos/citizenos-api/commit/fc2a6e3639c63d4530c03ec1ecf8b719421ed41c
    - [x] Re-vote - https://github.com/citizenos/citizenos-api/commit/fc2a6e3639c63d4530c03ec1ecf8b719421ed41c
    - [x] Vote counting - https://github.com/citizenos/citizenos-api/commit/fc2a6e3639c63d4530c03ec1ecf8b719421ed41c 
    - [x] Downloads
        - [x] User BDOC container -~~**TODO:** User container does not have all options, only 1.
![image](https://user-images.githubusercontent.com/7405383/77451588-88f2fa00-6dfd-11ea-9660-0585b47ca081.png)~~ https://github.com/citizenos/citizenos-api/commit/78c967cf04f0f42c6e40a7d1e14e9af48a7ae34b
        - [x] Final BDOC container - **TODO:** CSV does not reflect the multiple choices. AND User container does not reflect multiple choices

**Comment by tiblu** [comment]
**Conclusion**

* API has support for multiple-choice voting and verified with tests.
* FE needs new UX - https://github.com/citizenos/citizenos-fe/issues/413

Closing this, FE part is separate issue - https://github.com/citizenos/citizenos-fe/issues/413

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
