### ISSUE TITLE
Upgrade to Etherpad 1.8.3

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#466]
**What is the user story?**

Etherpad evolving quickly, code is being refactored and improvements made. We don't want to fall behind to a state where we cannot use official versions.

**What is the requested feature?**

Upgrade Citizen OS to use Etherpad 1.8.3

**Known issues**

* Etherpad 1.8.3 changed their visual appearance quite a bit, which in combination with Citizen OS specific stylesheets breaks the visuals of Citizen OS. We need to make new stylesheets to fit with Citizen OS visuals. **NOTE:** EP has custom skinning, research if we want to use that instead of plugin to override styles.

![image](https://user-images.githubusercontent.com/7405383/80487944-46758d80-8966-11ea-9df5-33e22b27d93c.png)

**Comment by loorm** [comment]
Triage 20 - need to do this, but because this is a lot of work, prioritize this for summer 2020. Est. developer hours 1 week, at least.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by tiblu** [comment]
@ilmartyrk Maybe checklist upgrading 1.8 is of https://github.com/citizenos/citizenos-api/issues/154 is of help.

**Comment by ilmartyrk** [comment]
@tiblu thank you, this is really helpful

**Comment by ilmartyrk** [comment]
**TODO**:
- [x] - Update locally
- [x] - Check if all plugins work or if some need some modifications
- [x] - Run tests in our API project to see if everything is OK
- [x] - Check manually if UI is working normally and as intended
- [x] - Check exported docx files in vote containers


**TESTING:**

Plugins:

- [x] ep_align
    * Updated to be in sync with original plugin, there were a lot of changes made by John
- [x] ep_auth_citizenos
    - [x] authenticated access
    - [x] non authenticated access - covered by API autotests
          * "Fail - Forbidden - User membership was revoked from Group"
          * "Success - User can read public Topic"
          * "Updated styles to display users list button and popup correctly"
- [x] ep_authorship_toggle
- [x] ep_comments_page - **depends on ep_inline_toolbar, ep_page_view**
    * Could not reproduce https://github.com/citizenos/citizenos-fe/issues/396 any more. 
- [x] ep_embed_floating_toolbar
    * Broke the toolbar in UI by adding default styles to toolbar
- [x] ep_font_color
- [x] ep_font_size
- [x] ep_foot_note
- [x] ep_headings2
- [x] ep_image_upload - **TODO:** AWS conf needed!
- [x] ep_inline_toolbar - **dependency of ep_comments_page, ep_inline_voting**
    * Updated positioning of toolbar, as it got broken
- [x] ep_inline_voting - **depends on ep_inline_toolbar.**
    * Missing icon, but that was before release - https://github.com/citizenos/citizenos-fe/issues/398
- [x] ep_page_view - **dependency of ep_comments_page**
- [x] ep_resize
- [x] ep_themes_ext
- [x] ep_title_limit
    * Little bugged, but was before EP upgrade. bug creaated - https://github.com/citizenos/ep_title_limit/issues/1
- [x] ep_webhooks
- [x] ep_translations - **TODO:** Verify that files are downloaded to the machine and in browser check for `html10n.translations`

Other:

- [x] Vote result download (docx)

**Comment by ilmartyrk** [comment]
@kevincrepin can you have a look, most of the plugins are updated to be in sync with their original projects and so the layouts and styles are also changed to use the original plugin functionality. I have added some styling from our side so that the fonts and text formating would look similar between our read and edit views. To get the best understanding what has changed you can compare editors in our test environment and live.
