### ISSUE TITLE
Bug: Topic title typing issues on mobile

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#535]
**What is the problem?**
When trying to edit the topic title on mobile, when creating a new topic, it reacts very badly with the autocorrect and creates long strings of gobbledygook like shown in the screenshot. It seems especially bad when using backspace to delete characters (adding more and more repetitions of the word/sections of the word instead) but also malfunctions when typing forwards. (It's just for the title though, typing in the body text seems to work fine). 

![Screenshot_20200731-145858](https://user-images.githubusercontent.com/61320526/89040109-84a69280-d343-11ea-8a15-341df32cdd65.png)

Video:

* ![Etherpad_ep_title_limit_mobile_text_randomness](https://user-images.githubusercontent.com/7405383/115889020-3b135000-a45c-11eb-9fe9-a4856496f804.gif)

Related to:

* https://github.com/citizenos/citizenos-fe/issues/676

**Comment by loorm** [comment]
Triage 24. Replicated. Cause unknown. Needs investigation. Prioritizing.

**Comment by ilmartyrk** [comment]
Seems to happen when backspace is held down to delete more text.

Info for debugging: 
User chromes inbuilt android debugging tool  setup link here https://developers.google.com/web/tools/chrome-devtools/remote-debugging

**Comment by ilmartyrk** [comment]
By testing at some other public instances and removing plugins from our test environment EP managed to narrow it down to ep_title_limit plugin. So the cause is in there, but how to solve it is not sure at least for now.

**Comment by loorm** [comment]
Triage 26. Estimated time 1 day. ep_title_limit plugin is the likely culprit.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.

**Comment by ilmartyrk** [comment]
Got it to work a little better, but far from ok. Marked it blocked till a better solution comes into mind.

**Comment by tiblu** [comment]
**TODO**

- [x] Verify that the issue is indeed with "ep_title_limit" - **DONE:** Removed "ep_title_limit" plugin in testing env and after that everything works great.
- [x] Update `etherpad.css` of CitizenOS FE project as `.ttl` changed to `ep_title_limit_ttl`
- [x] Get emulator/phone running against development environment - could not get phone run against local environment. I think I need to set up a router and configure routing/DNS from there. Both machines, DEV and phone connect to that router. **DID NOT DO**, no router with configurable DNS.
- [x] https://github.com/citizenos/ep_resize - ~~rewrite NOT TO USE JQuery. It seems using JQuery, calls internally `getById` (https://github.com/citizenos/etherpad-lite/blob/develop/src/static/js/vendors/jquery.js#L1140) which modifies DOM and causes `aceEditEvent`'s to trigger in loop.~~ The `aceEditEvent` loop is NOT caused by the DOM modifications of JQUERY, it is kinda "event loop" inside Etherpad (Ace) and I THINK it is as designed. 
- [x] https://github.com/citizenos/ep_resize - publish to NPM "ep_resize" from Citizen OS.
- [x] Fix error - `Uncaught TypeError: Cannot read property 'data' of undefined
at https://test.p.citizenos.com/p/c7e31f9b-3c39-4b04-98c2-35de8e1497d3?` on doc https://test.app.citizenos.com/en/topics/c7e31f9b-3c39-4b04-98c2-35de8e1497d3?editMode=true - seems to be related to `ep_comments_page` and localization. Reproduce in test: create an inline comment and reload the page with caches enabled. - https://github.com/ether/ep_comments_page/pull/198
- [x] release "ep_foot_note":
    - [x] Claim ownership
    - [x] Release in NPM - 0.1.0
    - [x] Use in Citizen OS deployments
    - [x] Update sample confs in etherpad-lite-heroku 
    - [x] Deprecate original "ep_foot_note" repository https://github.com/LokeshN/ep_foot_note

**Observations**

* IF the limit has been reached, the `ep_title_limit` constantly spams the server with changesets even when no changes have been done. That MAY cause the issue of weird editing (blocks dissapearing, reappearing) because of the changeset conflict resolution. 
![image](https://user-images.githubusercontent.com/7405383/112833761-d99bd380-909f-11eb-83b0-f908ae5cda97.png)
* IF "ep_title_limit" changes attributes, it sometimes causes "badChangeset" error as it tries to send the exact same changet twice. Which is interesting as the changesets are a bit different. **TODO:** Investigate changeset syntax!
    *  Server logs: 
    ```
    [2021-04-06 12:52:33.811] [WARN] console - Error: Can't apply USER_CHANGES, because Won't apply USER_CHANGES, as it contains an already accepted changeset
        at handleUserChanges (/home/m/dev/etherpad-lite-heroku/etherpad-lite/src/node/handler/PadMessageHandler.js:663:15)
        at process._tickCallback (internal/process/next_tick.js:68:7)
    ```
![image](https://user-images.githubusercontent.com/7405383/113696020-2b64df00-96da-11eb-8c9c-0a1811f944e4.png)
* In TESTING/LIVE, Users with 2 different devices - changes are not synced, gets an error
![image](https://user-images.githubusercontent.com/7405383/112853473-8f255180-90b5-11eb-8813-1c16620e4204.png)
* Mobile keyboard evens vs desktop keyboard events
    * When you HOLD down BACKSPACE to delete stuff:
        * PC (Chrome on Windows)
            * Spams ONLY "keydown" events, NO "keyup" until you actually let go of the key.
            * `evt.originalEvent.key="Backspace"` AND `evt.originalEvent.keyCode = 8`
![image](https://user-images.githubusercontent.com/7405383/113870000-09428e00-97ba-11eb-9d18-9d2a053743c0.png)

        * MOBILE (Chrome for Android)
            * Spams "keydown" AND "keyup" events.   
            * `evt.originalEvent.key="Unidentified"` AND `evt.originalEvent.keyCode = 229` (https://lists.w3.org/Archives/Public/www-dom/2010JulSep/att-0182/keyCode-spec.html)
![image](https://user-images.githubusercontent.com/7405383/113869907-ee701980-97b9-11eb-8aa1-ddceb172da44.png)
* How EP handles key events?
     * `$(document).on('keydown', handleKeyEvent); $(document).on('keypress', handleKeyEvent); $(document).on('keyup', handleKeyEvent); `
     *  When you HOLD down a key that produces a character button ("A", "B", "S" etc):
         * PC  (Chrome on Windows) 
             *  Spams "keydown" AND "keypress" events. 
             *  `evt.originalEvent.key="s"` AND `evt.originalEvent.keyCode = 83` 
![image](https://user-images.githubusercontent.com/7405383/113875319-4e1cf380-97bf-11eb-94b4-f03815febd0a.png)

         * MOBILE (Chrome for Android) 
             * NO EVENT IS TRIGGERED WHEN HOLDING. NO CHARACTERS. When RELEASED triggers "keydown" and "keyup".
             * `evt.originalEvent.key="Unidentified"` AND `evt.originalEvent.keyCode = 229` 
![image](https://user-images.githubusercontent.com/7405383/113876915-dd76d680-97c0-11eb-9918-80d714877c1d.png)
* What has effect on messing up text in mobile?
    * `doInsertTitleLimitMark` only calls `console.debug` - **NO GOOD**, still breaks exp.
    * `aceKeyEvent` - remove `setTimeout` around `callWithAce`? - **NO GOOD**, breaks. `VM96:410 Uncaught TypeError: Cannot read property 'type' of null` (https://github.com/ether/etherpad-lite/blob/8384a7a67bfb6db6256a117153d4b8e6f1098d20/src/static/js/ace2_inner.js#L406)
    * calls to `ace_callWithAce` inside `setTimeout` - **YES** Following snippet is enough to ruin mobile experience:
    ```
    setTimeout(function () {
        context.editorInfo.ace_callWithAce(function (ace) {
            console.debug('ep_title_limit', hook, context, 'ace_callWithAce');
        }, 'insertTitleLimitMark', true);
    }, 0);
    ```

**Comment by tiblu** [comment]
### Etherpad internals - the glossary

* **apool** - attribute pool - https://etherpad.org/doc/v1.8.13/#index_apool
* **atext** - Consists of text and attributes and operators. The text is just the text of the pad as a string. Attributes are just attributes used and operators describe the use of the attributes on that text  - https://etherpad.org/doc/v1.8.13/#index_atext

**Comment by tiblu** [comment]
**DONE**

UX:
* Behaves like the old version on physical keyboard devices (PC).
* On mobile, no coloring of overflowing text as this causes the weird behavior. 
* Now warning modal is ONLY shown on the screen of the user that types, not other collaborators.

Tech:
* Using `aceKeyEvent` instead of `aceEditEvent`. (https://github.com/citizenos/citizenos-fe/issues/535#issuecomment-805897450)
* Listening only `keydown` events.
* On virtual keyboard devices skipping attribute changes.
* Did not really understand why EP internals act up like this.
