### ISSUE TITLE
Pre-filled email field makes users think their email is connected with their ID code when choosing ID-card, Mobile ID or Smart ID as log-in option

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#657]
**What is the user story?**
After receiving an email invitation to the group or topic, user clicks on "Log-in / register Citizen OS account". Our system provides pre-filled email and password. User logs in with ID card, because s/he thinks that if the email address field is pre-filled (has a valid email address), then the email address and identification code are connected. She logs in with ID card but doesn´t get into the topic or group and is confused.

<img width="833" alt="Log-in" src="https://user-images.githubusercontent.com/45175679/112007171-1d855a80-8b2d-11eb-9b24-c17680ad3e25.png">

**Which feature needs to be updated and how?**
I would suggest to remove ID card, Mobile ID and Smart ID opportunities under the log-in options and leave only social log-in + COS account options.  Users wouldn´t get confused about the hard log-in specificities (which email is connected to their ID code and when our system does that). User who needs to participate in hard voting, has to identify herself with PIN2 anyway (and make extra activities for that). 

**Additional information.**
In case we don´t want to remove ID card, Mobile ID and Smart ID from sign-in opportunities, we could remove these options from users log-in window, who are invited to the group or topic via email.

**Comment by anettlinno** [comment]
Another user case that applies to same issue: user thinks that ID voting requires ID log-in and therefore, when person is invited to a group or topic, she thinks that she has to sign-in with her ID card, to give the hard vote.

**Comment by loorm** [comment]
Triage 36:
Use case 1. User has no Citizen OS account registered. When following link from e-mail invite, system will display register account dialog with e-mail field pre-filled.

Use case 2. User has a Citizen OS account with this e-mail. Login dialog window will check user connections and display all buttons, for which a user connection to this e-mail exists.

Estimated dev time 12 hours. Prioritizing.

**Comment by tiblu** [comment]
### TODO

#### UC 1 - NEW User

- [x] FE:  Show register form with pre-filled e-mail **BLOCKED** - https://github.com/citizenos/citizenos-fe/issues/657#issuecomment-829314888
- [x] FE: TESTING - Topic invite flow with registration -  API test to generate data: `Topics Invites Users Create Success - 20100 - invite a single User with non-existing e-mail`
    - [x]  E-mail is prefilled, password input focussed
    - [x] Auth methods filtered - Shows only CitizenOS login.
    - [x] Access resource invited to 
- [ ] FE: TESTING - Group invite flow with registration - API test to generate data: `Groups Invites Users Create Success - 20100 - invite a single User with non-existing e-mail`
    - [ ] E-mail is prefilled, password input focussed
    - [ ] Auth methods filtered - Shows only CitizenOS login.
    - [ ] Access resource invited to
    
#### UC 2 - Existing User

- [x] API: Get User connections - `GET /api/users/:userId/userconnections`. Outputs ONLY connection ID, no other info.
- [x] FE: Filter the login method list by the connections User has.
    - [x] Pass `userId` to FE `https://test.app.citizenos.com/en/account/login`
    - [x] IF `userId` IS present, call `GET /api/users/:userId/userconnections` to get the connections.
    - [x] Filter login methods
    - [x] Filter login methods on esteID modal, pass on the `availableMethods`
    - [x] Pre-fill e-mail IF User has "citizenos" connection. - **BLOCKED** - https://github.com/citizenos/citizenos-fe/issues/657#issuecomment-829314888
- [x] FE: TESTING - Topic invite flow - API test to generate data: `Topics Invites Users Create Success - 20100 - invite multiple users, 1 existing User and one not existing User - email & email`
     - [x] E-mail is prefilled, password input focussed
     - [x] Auth methods filtered
     - [x] Access resource invited to
- [x] FE: TESTING - Group invite flow - API test to generate data: `Groups Invites Users Create Success - 20100 - invite multiple users, 1 existing User and one not existing User - email & email`
     - [x] E-mail is prefilled, password input focussed 
     - [x] Auth methods filtered
     - [x] Access resource invited to

#### GENERAL

- [x] API: `GET /api/invite/view` is it actually used any more? Can it be removed? - Separate task - https://github.com/citizenos/citizenos-api/issues/203
- [x] Mapping APIs `UserConnection.connectionId` to FEs config authentication id. **DONE:** Mapped on FE side, we SHOULD be handling it in the backend somehow, but this needs longer discussion and bigger rewrite.

| UserConnection.connectionId  | FE config authentication id |
| ------------- | ------------- |
| esteid  | **mobiilId, idCard** |
| smartid  | **smartId** (camelCase)  |
| google | google |
| facebook | facebook  |
| citizenos | citizenos |
 
- [x] Should I be worried about `GET` parameters containing private info?  **YES** - https://github.com/plausible/analytics/discussions/136
    - [x]  Make sure no sensitive info is passed in GET parameters
- [ ] Test read-only access Pads

**Comment by tiblu** [comment]
### How invite flow works

* User gets an e-mail with link that leads to FE - https://test.app.citizenos.com/en/topics/:topicId/invites/users/:inviteId
* FE requests API  `GET /api/topics/:topicId/invites/users/:inviteId` to get Invite info:
```
{
   "id":"d0b870c8-c3ad-4997-a129-b1ba8599f085",
   "topicId":"f54793d0-c762-407b-8000-2fa26860e6df",
   "userId":"87e6234c-f27c-4ac7-898d-9606134c24ba",
   "creatorId":"a2ec7997-8559-480f-b865-7f1adc323508",
   "level":"admin",
   "createdAt":"2021-04-29T13:30:25.125Z",
   "updatedAt":"2021-04-29T13:30:25.125Z",
   "topic":{
      "id":"f54793d0-c762-407b-8000-2fa26860e6df",
      "title":"TEST INVITES #657",
      "visibility":"private",
      "creator":{
         "id":"a2ec7997-8559-480f-b865-7f1adc323508"
      }
   },
   "creator":{
      "id":"a2ec7997-8559-480f-b865-7f1adc323508",
      "name":"Bat Zorro",
      "company":"Tiblu OÜ",
      "imageUrl":"https://lh3.googleusercontent.com/-YmRjcQJ88Dc/AAAAAAAAAAI/AAAAAAAABWg/gCKdNoNjR3o/photo.jpg"
   },
   "user":{
      "id":"87e6234c-f27c-4ac7-898d-9606134c24ba",
      "email":"ti******@hot.ee"
   }
}
```
* Depending on the login state:
     * NOT logged in:
          * FE shows modal: 
![image](https://user-images.githubusercontent.com/7405383/116560879-786b5800-a90a-11eb-8096-e4a8f1e079eb.png)
          * User clicks to "Log in" and e-mail is passed to login to pre-fill the e-mail form.
          * User logs in and is redirected back to the same ` https://test.app.citizenos.com/en/topics/:topicId/invites/users/:inviteId` where "IS logged in" flow takes over.
     * IS logged in
          * The invited User
              * FE calls API `POST /api/topics/:topicId/invites/users/:inviteId/accept` to accept the invite.
              * Redirects to FE `/topics/:topicId`
          * NOT the invited User
              * Logs out
              * Redirected back to the same ` https://test.app.citizenos.com/en/topics/:topicId/invites/users/:inviteId` to beginning of the flow. The "NOT logged in" flow is executed.

**Comment by tiblu** [comment]
@KatiVellak

For invites we:

* Send e-mail to User with a link.
* This link opens up following modal in Citizen OS 
![image](https://user-images.githubusercontent.com/7405383/116573105-34ca1b80-a915-11eb-9683-be541311e7a9.png)

Question: 

* Is it OK if we show FULL e-mail in the invitaion text instead of the censored version? 

Why am I asking?

* We would like to filter login methods by the Users available login methods. That means we need to ask for these methods by e-mail address. To do so, we need to know in the browser the full e-mail.
* We would like to prefill login form with the actual e-mail address the User was invited with.

**Comment by tiblu** [comment]
### Release notes

- [x] `ep_auth_citizenos` - release due to `readOnly` headers already sent bug.
- [x] Etherpad to use `ep_auth_citizenos@1.0.3`
    - [x] TEST
    - [x] PROD
- [x] release API
    - [x] TEST
    - [x] PROD
- [x] release FE
    - [x] TEST
    - [x] PROD


### Issues while testing

#### TEST

- [x] `2021-05-06T15:10:27.524136+00:00 app[web.1]: [32m[2021-05-06T15:10:27.524] [INFO] test - [39mSequelize error handler middleware activated. TypeError: Cannot read property 'id' of null` - caused by DB cleanup causing inconsistent data.

**Comment by tiblu** [comment]
**DONE**

Released to live.

**Implementation notes:**

* IF invite is received by an EXISTING User, User will be shown all authentication methods (FB, Google, Smart ID...) that his/her account is related to.
* IF invite is received by a NON-EXISTING User, User is ONLY shown email/password (citizenos) login authentication method and  redirected to registration flow once trying to log in/register.
* The behavior applies to both Topic and Group invite flows.

@anettlinno  please have a look if the solution satisfies you. Please do check new and existing User flows.

**Comment by tiblu** [comment]
> With an existing user I logged in with an email account where the invitation was sent and I had only two log-in options (I even didn´t know that my FB account is engaged with my gmail account :smile:). After logging out and clicking on the "Log-in" button again I received only log-in box but no log-in options (picture below). It only happened once and after I closed all COS windows, refreshed the page and clicked on the log-in button again, normal log-in options were displayed.

@anettlinno 

Could not reproduce. Tried the following:

* Case 1: Logged in with existing User, logged out and logged in again. The list of methods looked ok.
* Case 2: Invited existing User to a Topic. Opened invite, logged in, logged out and logged in again. The list of methods looked ok.

**Comment by KatiVellak** [comment]
@tiblu yes, it is okay if we show full e-mail in the invitation text instead of the censored version. In such case we can filter login methods by the Users available login methods and ask for these methods by the known full e-mail address. And in such case we are able to prefill login form with the actual e-mail address the User was invited with.
