### ISSUE TITLE
Show members email addresses to group/topic admin

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#670]
**What is the user story?**
The administrator of the group or topic wants to update the email addresses of the members but they only see the user name and user rights but not the email addresses that members have been invited to the group/topic. As a group/topic administrator have the user list anyway (they have invited all members into the group/topic), then users emails could be shown to them.

<img width="552" alt="User list" src="https://user-images.githubusercontent.com/45175679/112167931-889c6300-8bf9-11eb-9022-82babaac10dd.png">

**Which feature needs to be updated and how?**
Show group/topic admin members´ email addresses.

**Additional information.**
Needs input about how it resonates with GDPR :)

**Comment by loorm** [comment]
Triage 36. @kativellak please review. If we implement this, it would apply to **all** admin members of the topic, not just one. So if a topic or group has multiple admins, all would see e-mails of all members. Can we do this? Would showing a partial e-mail address (with some bits hidden) be an acceptable workaround?

**Comment by KatiVellak** [comment]
@anettlinno and @loorm could you elaborate the need and purpose for the admins to see emails of all members? I am happy to take a quick call on this to speed things up :) .

**Comment by loorm** [comment]
Since the issue was created by @anettlinno, based on user feedback she received, I will now leave it in her hands as the new product owner, to see this issue through.

**Comment by anettlinno** [comment]
Triage 47. Hight priority development. Est. dev. time 4 days. Sending to development together with #239.

**Comment by anettlinno** [comment]
Triage 48. This will be solved together with #239.

**Comment by KatiVellak** [comment]
Discussed and it is justified for the admins to see the emails of participants of topic.

**Comment by tiblu** [comment]
@anettlinno @ilmartyrk @kevincrepin 

Questions:

- Has there been any discussion about where the info would be shown?
- IF email does not exists, is it justified to show phone?

**Comment by ilmartyrk** [comment]
What I understood from @KatiVellak is that we have enough reasons to display users contact info for admins be it e-mail or phone. I believe the initial problem was that it was difficult for admins to be sure who is who as user might have random e-mail address and different user name. Or there  can be users with same name, but different address.

Long story short I believe it's OK to display phone for users who don't have e-mail address. Can you confirm it @KatiVellak ?

**Comment by tiblu** [comment]
## TODO

Following API-s MUST return e-mail / phone for ADMIN members ONLY IF the info exists:

- [x] API `GET /api/users/:userId/topics/:topicId/members/users`
- [x] API `GET /api/users/:userId/topics/:topicId/members`
- [x] API `GET /api/users/:userId/topics/:topicId/invites/users`
- [x] API `GET /api/users/:userId/groups/:groupId/members/users`
- [x] API `GET /api/users/:userId/groups/:groupId/invites/users`

FE:

- [x] Display user info
    - [x]  My Topics
        - [x] Member list
        - [x] Pending invites
    - [x]  My Groups
        - [x] Member list
        - [x] Pending invites

**Comment by KatiVellak** [comment]
@ilmartyrk @tiblu I can confirm phone number is justified to show if there is no email to show.

**Comment by tiblu** [comment]
> @ilmartyrk @tiblu I can confirm phone number is justified to show if there is no email to show.

@KatiVellak Sorry, forgot about PID (et: "isikukood"). Is that safe to show? This is the case where User has only used ID-card login.
While the showing of PID does not give communication channel, it gives an idea which login User has used and helps on debugging the membership issues.

**Comment by tiblu** [comment]
> ## TODO
> Following API-s MUST return e-mail / phone for ADMIN members ONLY IF the info exists:
> 
> * [x]  API `GET /api/users/:userId/topics/:topicId/members/users`
> * [x]  API `GET /api/users/:userId/topics/:topicId/members`
> * [x]  API `GET /api/users/:userId/topics/:topicId/invites/users`
> * [x]  API `GET /api/users/:userId/groups/:groupId/members/users`

API part has been released 05.11.2021.

**Comment by anettlinno** [comment]
> @anettlinno @ilmartyrk @kevincrepin
> 
> Questions:
> 
> * Has there been any discussion about where the info would be shown?
> * IF email does not exists, is it justified to show phone?

All the information that we know about the user should be held in "My account" so that user would know what we know and could control what kind of information s/he gives out :) 
User email address should be shown under Users list (both under General Information and under the Options) ONLY to admin users. This topic is closely related with #239. 

We don´t currently ask email or phone number in registration link but this problem will be solved with issue #588 where we ask email address if user is registering with eID. So, I think that in this light we should not ask phone number (we do have a separate issue for asking more information from users #521).

**Comment by tiblu** [comment]
## Feature released 11.11.2021

![CitizenOS_gh_670](https://user-images.githubusercontent.com/7405383/141329902-7a7862e8-7e7d-4974-95e9-219e075fc6dc.PNG)

### Implementation notes

* Apples to member list and pending invites for both Topics and Groups on Dashboard.
* Extra contact info is ONLY shown for:
    * Admin members of the Topic/Group
    * Global Moderators

**Comment by anettlinno** [comment]
Tested and works nicely 👍 

I would like to check with @KatiVellak if showing ID numbers is OK (even if only Admin members of Topics/Groups), because on our last Triage meeting Kati said that we shouldn´t show ID numbers. Looking for you comment, @KatiVellak :)

**Comment by tiblu** [comment]
@anettlinno  I will clean up the PID-s.

**Comment by tiblu** [comment]
@anettlinno @KatiVellak PIDs are not returned by the API and not shown in the UI any more.

**Comment by anettlinno** [comment]
> @anettlinno @KatiVellak PIDs are not returned by the API and not shown in the UI any more.

Thanks a lot! Showing only emails is solving the initial issue.
