### ISSUE TITLE
ETHERPAD: Collaborative editor broken when 2 users create session in same browser - no changes visible to collaborators, errors on screen

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#676]
**What is the problem?**
Etherpad collaborative editing is broken, other Users do not see changes, but get an error message.

**UPDATE:** Issue only occurs when you try to access same Pad with different Users in same browser.  What happens is `ep_auth_citizenos` invalidates current session when User accesses Pad, so in the other browser window, the session is not valid any more and gets this weird error. BEFORE 1.8 version, User would see "Connection lost, reconnect to Pad" modal.

**Reproduce**

* User 1 - Create Topic
* User 1 - Invite another User 2 with "edit" permissions.
* User 1 - Open Topic in "edit" mode.
* User 2 - accept the invite.
* User 2 - Open Topic in "edit" mode.
* User 1 - Edit Topic text
* User 2 - No changes visible, error on screen!

![image](https://user-images.githubusercontent.com/7405383/112854556-a4e74680-90b6-11eb-9cdf-fa7231f01993.png)

**Why is this a problem?**
Basic functionality is broken.

**Possible solution.**

* Do we want to allow people to work on the same Pad in different browser windows?
     *  YES: We need to go deep and see if we can make it. Probably extra customized ep_auth_citizenos would enable it, but MAY be quite a bit of work.
     *  NO: We need to fix EP so that if auth fails, it shows "Reconnect" or some other meaningful message, it SHOULD NOT be JavaScript error.

What did not work in terms of getting the old "reconnect" behaviour back:

* Etherpad update to 1.8.13 - was nice move anyway, got some plugins sorted out.

**Comment by tiblu** [comment]
**Investigation**

Interesting, login as same User for the same PAD in different browsers - Chrome & IE.
When I post as the same User from 3rd client - Chrome mobile - Chrome client sees different WS messages and throws an error while IE works fine.

![image](https://user-images.githubusercontent.com/7405383/112985414-d1f43180-9168-11eb-8900-b88e48b4a532.png)

When looking at public instance of EP on https://etherpad.wikimedia.org/p/test:

* Editing client should:
    * Send "USER_CHANGES" message.
    * Receive "ACCEPT_COMMIT"
* Viewing client should:
    * Receive "NEW_CHANGES" message.

BUT, on https://test.app.citizenos.com:

* Editing client sends:
    * Send "USER_CHANGES" message.
    * Receive "ACCEPT_COMMIT"
* Viewing client:
    * **Receive "ACCEPT_COMMIT" ONLY**

Possible causes:

* I THINK "ep_auth_citizenos" terminates EP session when User logs in from another window, BUT since EP 1.8.x it does not handle the disconnect as it used to, the socket remains open, browser does not warn user that he has been disconnected. As the socket is open, some messages still flow, not all, but some - "USER_CHANGES" dont (as expected, there is no session), but somehow "ACCEPT_COMMIT" messages do appear and the FE is confused.

**Comment by tiblu** [comment]
## Upgrading EP 1.8.13

### Issue 1 - patch version update does not support `dbSettings` to be a string any more. 👍
Ueberdb2 deps:
* 1.8.13 - 1.4.4
* 1.8.7 - 0.5.6

```
[2021-03-30 17:02:44.947] [INFO] console - Random string used for versioning assets: 686d8541
/home/m/dev/etherpad-lite-heroku/etherpad-lite/src/node_modules/ueberdb2/databases/postgres_db.js:24
  this.settings.cache = settings.cache || 1000;
                      ^

TypeError: Cannot create property 'cache' on string 'postgres://etherpad:etherpad@localhost:5432/etherpad'
    at new exports.Database (/home/m/dev/etherpad-lite-heroku/etherpad-lite/src/node_modules/ueberdb2/databases/postgres_db.js:24:23)
    at new exports.Database (/home/m/dev/etherpad-lite-heroku/etherpad-lite/src/node_modules/ueberdb2/index.js:60:14)
    at Object.<anonymous> (/home/m/dev/etherpad-lite-heroku/etherpad-lite/src/node/db/DB.js:32:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

Created a bug - https://github.com/ether/etherpad-lite/issues/4985

### Issue 2 - need to update our `ep_auth_citizenos` plugin 👍

```
[2021-03-30 19:10:01.440] [ERROR] server - Error: DOUBLE SETTLE BUG IN HOOK FUNCTION (plugin: ep_auth_citizenos, function name: /home/m/dev/etherpad-lite-heroku/etherpad-lite/node_modules/ep_auth_citizenos/serverHooks:preAuthorize, hook: preAuthorize): Attempt to resolve via returned value but it already resolved via callback. Ignoring this attempt to resolve.
    at settle (/home/m/dev/etherpad-lite-heroku/etherpad-lite/src/static/js/pluginfw/hooks.js:251:17)
    at Promise.resolve.then (/home/m/dev/etherpad-lite-heroku/etherpad-lite/src/static/js/pluginfw/hooks.js:319:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Issue 3 - need to update our `ep_auth_citizenos` plugin 👍

```
[2021-03-30 19:49:04.685] [ERROR] server - Error: DOUBLE SETTLE BUG IN HOOK FUNCTION (plugin: ep_auth_citizenos, function name: /home/m/dev/etherpad-lite-heroku/etherpad-lite/node_modules/ep_auth_citizenos/serverHooks:authorize, hook: authorize): Attempt to resolve via returned value but it already resolved via callback. Ignoring this attempt to resolve.
    at settle (/home/m/dev/etherpad-lite-heroku/etherpad-lite/src/static/js/pluginfw/hooks.js:251:17)
    at Promise.resolve.then (/home/m/dev/etherpad-lite-heroku/etherpad-lite/src/static/js/pluginfw/hooks.js:319:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Added docs how to develop plugins with Etherpad-Lite-Heroku - https://github.com/citizenos/etherpad-lite-heroku#developing-and-testing-ep-plugins-with-this-project

**Comment by tiblu** [comment]
Related to: https://github.com/ether/etherpad-lite/issues/4985

**Comment by tiblu** [comment]
![image](https://user-images.githubusercontent.com/7405383/116524210-cc147c00-a8df-11eb-9f0f-4a8fd3d629c4.png)

**Comment by loorm** [comment]
Triage 36. Replicated. In case logged into and editing one and the same topic from two different users. Prioritizing (low priority). Purpose - restore "Force reconnect" feature in Etherpad, if possible.

**Comment by tiblu** [comment]
## Investigation

* `ACCEPT_COMMIT` message is sent to both Users PADs as both have same `author` - https://github.com/ether/etherpad-lite/blob/5db0c8d1cfc3f354a5a8badce6d5c3890d428e98/src/node/handler/PadMessageHandler.js#L742
* Both sockets exists and are valid after User logs in to a Pad with same User from different browsers.
* With VANILLA EP, without auth, the EP will throw "Opened in another window" dialog - https://etherpad.wikimedia.org/p/citizenostest 
![image](https://user-images.githubusercontent.com/7405383/118652649-78ff5c00-b7ef-11eb-9aba-ce34ced57657.png)
    * FE reacts to sockets "disconnect" message `["message",{"disconnect":"userdup"}]`
* IF I do not delete the `token` cookie in ep_auth_citizenos (https://github.com/citizenos/ep_auth_citizenos/blob/4f806857cfa0e8c907ba67dc955f138a3afa917b/serverHooks.js#L317) then same browser instance will give the correct "Opened in another window" error, BUT if the instance is In-cognito or otherwise not aware of the `token`, the JS error will still appear. So, it seems like the "Other window check" is based on "token" to "author" mapping, if the token does not exist, new token and author is generated.
* Cookie `token` is generated by FE and sent to server with `clientReady` message. Src: https://github.com/ether/etherpad-lite/blob/6f2f20233f389dc63e7f9435232a9778da453fec/src/static/js/pad.js#L199
* `clientVars.userId` === `authorID`
* > A CLIENT_READY is the first message from the client to the server. The Client sends his token and the pad it wants to enter. The Server answers with the inital values (clientVars) of the pad
    * Src: https://github.com/ether/etherpad-lite/blob/b040ebf41932d8d74e089abdcad6ad1fdb1bee37/src/node/handler/PadMessageHandler.js#L866 
* Hook `clientVars` runs AFTER `authenticate` & `authorize` hook.
* Hook `clientVars` runs AFTER `handleClientReady` (`userdup` check)

### Questions:

- [ ] Should `ACCEPT_COMMIT` be sent not comparing `author`, but something else? Like is the that the send and receive socket ID-s are the same?
- [ ] Should `ep_auth_citizenos` somehow invalidate/kill the socket when User leaves? Should EP clean up? I think EP should, but is not?

**Comment by tiblu** [comment]
## TODO

- [x] ep_auth_citizenos - `GET /ep_auth_citizenos/logout`
    - [x] CORS  
- [x] Citizen OS FE - FE logout to call `/ep_auth_citizenos/logout`
    - [x] Success handling
    - [x] Error handling 
    - [x] Configurable URL for EP logout


## Release order

- [x] ep_auth_citizenos (1.0.5)
- [x] etherpad_lite_heroku config - add /logout with new version of ep_auth_citizenos in plugin config.
```
  "ep_auth_citizenos": {
    "___version": "1.0.5",
    "api": {
      "cors": {
        "origin": [
          "\\.citizenos\\.com(:[0-9]{2,4})?$"
        ],
        "credentials": true
      }
    },
  },
```
- [x] Citizen OS FE - config changes - CSP (`CSP_POLICIES`) + EP url (`CITIZENOS_ETHERPAD_BASEURL`)
```
{
"default-src": ["self", "'report-sample'"],
"img-src": ["*"],
"script-src": ["self", "https://cdn.crowdin.com", "https://apis.google.com", "'report-sample'"],
"style-src": ["self", "https://fonts.googleapis.com", "https://maxcdn.bootstrapcdn.com"],
"script-src-elem": ["self", "'report-sample'"],
"font-src": ["self", "https://fonts.gstatic.com", "https://maxcdn.bootstrapcdn.com"],
"connect-src": ["self", "https://id-test.citizenos.com", "https://test.api.citizenos.com", "https://test.p.citizenos.com", "https://sentry.io", "https://graph.microsoft.com"],
"base-uri": ["self"],
"object-src": ["none"],
"frame-src": ["https://test.p.citizenos.com", "https://accounts.google.com/", "https://docs.google.com"]
}
```
- [x] Citizen OS FE - call EP logout
- [ ] Citizen OS API (removal of clearing cookies on /logout).

## Testing

### Dev

- [x] New Citizen OS user
- [x] Existing Citizen OS user
    - [x] Create pad
    - [x] Edit pad
    - [x] Edit 2 different pads at the same time
    - [x] "Opened in another window" EP dialog when visiting same pad from 2 different windows  
- [x] User editing different pads at the same time
- [x] 2 Different users editing the same pad.
- [x] View timeline and come back to edit mode AFTER JWT expiry (1m)
- [x] Reconnect AFTER JWT expiry (1m)
- [x] Duplicate login from different browsers - expect to show "Opened in another window" EP dialog. Pad to be RO.
- [x] Login, logout, login with different User
    - [x] FIX: `express_sid` / `token` is hanging User is not overwritten, previously logged in user permissions used for editing. - FE to call `GET /ep_auth_citizenos/logout` on logout to destroy EP session.
- [x] Clean up `token` from DB on `userLeave`
- [x] Read-only view of a public Pad

### Test

- [x] New Citizen OS user
- [x] Existing Citizen OS user
- [x] User editing different pads at the same time
- [x] Duplicate login from different browsers - expect to show "Opened in another window" EP dialog. Pad to be RO.
- [x] Login, logout, login with different User
- [x] View timeline and come back to edit mode
- [x] Read-only view of a public Pad

### Prod

- [ ] New Citizen OS user
- [ ] Existing Citizen OS user
- [ ] User editing different pads at the same time
- [ ] Duplicate login from different browsers - expect to show "Opened in another window" EP dialog. Pad to be RO.
- [ ] Login, logout, login with different User
- [ ] View timeline and come back to edit mode
- [ ] Read-only view of a public Pad

**Comment by tiblu** [comment]
### Done

* 1 User can be logged and edit 1 Pad (Topic) from 1 single location. IF a Pad (Topic) is opened from new location, previous location socket is destroyed AND "Reconnect" action becomes available. When reconnect is used, Pad becomes editable in that location and the other location gets "Reconnect" and so on.
* On logout CitizenOS FE calls `GET /ep_auth_citizenos/logout` of the ep_auth_citizenos plugin to log out from Etherpad.
