### ISSUE TITLE
BEFORE 27.04.2021 - Switch to automated certificate management on all CitizenOS apps

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#688]
**What?**

Use automated certificate management for all CitizenOS apps.

**TODO**
- [x] test.app.citizenos.com - Heroku
- [x] test.api.citizenos.com - Heroku
- [x] test.p.citizenos.com - Heroku
- [x] app.citizenos.com - Heroku
- [x] api.citizenos.com - Heroku
- [x] p.citizenos.com - Heroku
- [x] dds.citizenos.com - Remove
- [x] id.citizenos.com - DO
- [x] id-test.citizenos.com - DO
- [x] mobiilid.citizenos.com - DO
- [x] ocsp.citizenos.com - DO
- [x] smartid.citizenos.com - DO

**Resources**

* https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-18-04

**Comment by ilmartyrk** [comment]
Digitalocean tasklist 

- [x] Backup
- [x] Remove unused services
- [x] Update Ubuntu  
     - [x] 16.04
     - [x] 18.04
- [x] Check if servers are working as should, after update
- [x] Install certbot
- [x] Create certificate
- [x] Update certificate paths in server configs
- [x] Restart and confirm everything is working

**Comment by ilmartyrk** [comment]
Updated Ubuntu to 18.04, Updating to 20.04 failed sending logs to rapid7 installed Certbot and updated all configs. Also got id-test running again as it wasn't working properly (config mismatch in heroku and on id server)
