### ISSUE TITLE
Flagging invited emails that are in the wrong format

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#704]
Am now separating this out into a new topic, and have removed it from where it previously was, in issue #694. This relates to FAQ 6 "Can I see if any of the email addresses I invited to a group or topic bounced?".

The problem: Currently if someone enters an email in an incorrect format (e.g. hello@gmail) the system just silently rejects it, without explaining what has happened. This means if someone enters 10 email addresses, they might not notice their are only 9 in the invites list before sending, as 1 of them was entered in an incorrect format.

A solution: I would suggest that when someone enters an email address in an incorrect format, a red outline and message should appear underneath the email invite field. Eg. “Oops, hello@email is not a correct email format.” Or “Oops, hello@email, hi@email and hola@email are not correct email formats” if multiple. (If we do this, then we can remove the bit about email from the above Guidance button and make it much shorter and simpler).

![image](https://user-images.githubusercontent.com/61320526/117488969-493d9200-af6d-11eb-98d6-723bb2b01262.png)

We (me, @tiblu @ilmartyrk, in meeting on 06.05) discussed this and agreed that:
- Emails in the wrong format (e.g. hello@gmail) should be included in “pre-sending” list (rather than "silently dropped"), but flagged up as invalid. 
- The ones which are invalid format should be at the top of the list so they are not missed by the user. However there should also be an error message, like in the mockup above. 
- This needs some thinking through as to how it would work technically and some @kevincrepin.

**Comment by loorm** [comment]
Triage 37. Development approved, however, need views from @kevincrepin. Moving to in prep until then. Once we have views, can go directly into dev without further triage.

**Comment by kevincrepin** [comment]
I might be missing something but why do we want to allow users to invite with wrong format email addresses? Just so we would show it in the list saying it's a wrong format?

Can't we use the field validation as Becca describes above but then not allow the user to add this wrong email address?

![Screenshot 2021-05-26 at 13 38 35](https://user-images.githubusercontent.com/26792281/119646312-b2574d80-be27-11eb-9c64-e43e089d8b56.png)

**Comment by ilmartyrk** [comment]
@kevincrepin, we actually allow pasting a list of emails into this field eg. ilmar@citizenos, margo@citizenos ..., then code parses out all valid emails and throws out all that are invalid. This was added to allow bigger organizations to add multiple users without separately having to input every email. We thought that these big lists can possibly contain typo-s and we could display these invalid emails in a separate list where user can fix typos. IF typos aren't fixed these addresses will be ignored otherwise they'll be added to valid users list

**Comment by kevincrepin** [comment]
Thanks for clarifying! So I'm thinking something like this then: https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=99%3A178

we show the invalid emails in a list and they're immediately editable. Correcting the wrong format should then make it possible to add them.

**Comment by ilmartyrk** [comment]
@kevincrepin  thanks, I just want to clarify how to communicate this action to user. Should we add extra button or use enter key? Also should we add red border while the value is still invalid?

**Comment by kevincrepin** [comment]
Since we don't have an add button in the first input – and I removed this add button now from designs to be more consistent – then I would say let's use the same method? Otherwise it's a bit weird for me to have here an add button but with the general input. 

I didn't make the inputs red because then we have a lot red and it feels very negative. that's why only the alert is red.

wdyt?

![Screenshot 2021-05-26 at 15 47 07](https://user-images.githubusercontent.com/26792281/119662085-a83e4a80-be39-11eb-9def-0b25c13a6200.png)

**Comment by ilmartyrk** [comment]
@kevincrepin, this sounds reasonable, but just to clarify, if a user still tries to add value that is incorrect, then the this single input will go red or do you have any other suggestions?

**Comment by kevincrepin** [comment]
Yes, let's do it so. Single invalid input triggers the field validation. Multiple input amongst which there can be invalid ones does not trigger the field validation but shows them in the list.

**Comment by BeccaMelhuish** [comment]
All sounds/looks good to me!

So just to clarify - if someone enters only one incorrect email formats it looks like this? 

![image](https://user-images.githubusercontent.com/61320526/119688054-92cc1f00-be3f-11eb-9c8b-3314fbbab94b.png)

But if several incorrect email formats it looks like this, and the blue "press enter etc" only appears once it has been entered in a correct format? 

![image](https://user-images.githubusercontent.com/61320526/119688270-be4f0980-be3f-11eb-8ca0-1e8161994aec.png)

This sounds fine, though I'm wondering if it wouldn't be more straightforward (for Ilmar to code and potentially for the user to understand) if it always looks like the first version above, and if there is more than one email address that are incorrect are all left standing in the box, e.g. like in the image below. And that they just correct them there and press enter again. Any ones that still aren't correct, the same thing happens again with whichever one(s) are still incorrect. Until they get them all sorted out. 

![image](https://user-images.githubusercontent.com/61320526/119689364-b17ee580-be40-11eb-8532-80c1530a96ee.png)

(The main reason for suggesting this is I feel perhaps this below only appearing when the email is correct could be confusing to users (they don't see how they will add until they've edited) but just a hunch, perhaps it's fine.) 

![image](https://user-images.githubusercontent.com/61320526/119690173-5c8f9f00-be41-11eb-9854-edcd14910630.png)


And only minor suggestion from me would be to change the text in the below to "Invalid email formats found". As the system only knows that it's an invalid email format, not if it's a valid format but will actually bounce (incorrect username for example). 

![image](https://user-images.githubusercontent.com/61320526/119687480-28b37a00-be3f-11eb-8078-4ecf43d644c1.png)

**Comment by loorm** [comment]
@kevincrepin, this needs some more attention from you. Becca has some additional ideas. WDYT?

**Comment by kevincrepin** [comment]
@BeccaMelhuish 
_(they don't see how they will add until they've edited) but just a hunch, perhaps it's fine.)_ this is also the way how they add it now though :)

I totally get your point and I also thought it could be a good way to go, but the only problem I could see is that since the original input field is limited in width, potentially several wrongly formatted email address might not even be visible. Considering that we're dealing with this case of pasting many emails into the field, I think that constraining the ones with wrong formatting in the existing input might be a bit confusing still.

But Maybe we can still make it clearer that these wrongly formatted email inputs should be dealt with: https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=180%3A17837

I can also make some prototypes if we want to test which version would seem more clearer, but it's a difficult one to test, since it relies heavily on user's own input...

**Comment by ilmartyrk** [comment]
@kevincrepin, really like it,  something like that was in my mind too

**Comment by loorm** [comment]
Triage 39. This is now ready for dev. Estimated dev time 16 hours. Prioritizing.

**Comment by BeccaMelhuish** [comment]
Hey @ilmartyrk just saw that this was moved to Done and closed, so gave it a little test, but it doesn't seem to be any different?  When entering a line of 3 emails, on incorrectly formatted it just "silently drops" the wrong format one again (see below). (Sorry if I'm jumping the gun, let me know when ready and I'll try again). 

![image](https://user-images.githubusercontent.com/61320526/122208099-ca584500-ce9a-11eb-836d-c2b12f41362a.png)

Also, would like to bring up the issue with this only appearing when the emails are entered correctly:

![Uploading image.png…]()

As I had entered one of the emails incorrectly, the above text didn't appear, and I automatically clicked the big "save topic" button, rather than pressing enter (it's more intuitive that that should be how it works - clicking the big shiny button right underneath). At which point of course the box closed and my invites weren't sent. Obviously I knew to go back and do it again and to press enter instead, but other users wouldn't know that, and would either assume their invites had been sent, or be unsure whether or not they had, and get confused/stressed out. 

![image](https://user-images.githubusercontent.com/61320526/122207784-6a619e80-ce9a-11eb-9561-156f85a39edc.png)

So @kevincrepin my feeling is this "press enter to add" doesn't work, and it would be better to just have an add button? Which is always there, and always active, but if they enter a wrong email format then all that we discussed above would happen. What do you think?

**Comment by BeccaMelhuish** [comment]
Hey @ilmartyrk just saw that this was moved to "Done" and closed, so gave it a little test, but it doesn't seem to be any different?  When entering a line of 3 emails, on incorrectly formatted it just "silently drops" the wrong format one again (see below). (Sorry if I'm jumping the gun, let me know when ready and I'll try again). 

![image](https://user-images.githubusercontent.com/61320526/122209559-90883e00-ce9c-11eb-9e56-c09aa4283a89.png)

Also, would like to bring up again the issue with the "press enter or click to add" only appearing when the emails are entered correctly:

As I had entered one of the emails incorrectly, the above text didn't appear, and I automatically clicked the big "save topic" button, rather than pressing enter (it's more intuitive that that should be how it works - clicking the big shiny button right underneath). At which point of course the box closed and my invites weren't sent. Obviously I knew to go back and do it again and to press enter instead, but other users wouldn't know that, and would either assume their invites had been sent, or be unsure whether or not they had, and get confused/stressed out. 

![image](https://user-images.githubusercontent.com/61320526/122209886-ed83f400-ce9c-11eb-98d0-19c885aafd43.png)

So @kevincrepin my feeling is this "press enter to add" doesn't work, and it would be better to just have an add button? Which is always there, and always active, but if they enter a wrong email format then all that we discussed above would happen. What do you think?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish sorry about that, github automatically closes the issue when word FIX is included in commit message, currently it is in test environment

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Ah right I see! :)

**Comment by BeccaMelhuish** [comment]
Hi @ilmartyrk! Am working out what to test as part of the first Help Centre design test (we'll give the users tasks to do which they might struggle with and therefore have need of using the Help Centre, and this will give us useful insights on those issues in turn). 

So am wondering if testing these changes is something that could be included (tests will be next week and/or the week after)?  You mentioned above that it was in the test environment, so perhaps that means almost ready?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish if by these changes you mean changes in this issue, then they are already in live environment. The issue with closed issues being in test and not live sometimes is that we include reference to the issue in the git commit message. And when I push the changes from my local machine to server the github AI sees the commit message and closes the issue automatically. Our own automation first pushes these updates to our test environment where we check if everything is as it should be in server too. And if there are no issues we manually push the changes to live. But that usually leaves a portion of time where issue is visibly closed, but the changes are not live yet. If we detect any issues in our testing environment we usually manually open the issue again, but if not then I usually don't see the point of changing the status for the time of in test -> production.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk ah OK! Actually the reason I asked is because I tested it out by writing one incorrectly formatted email address "bec@gmail", and found that it was just "silently dropped" again. But I now see that it works when you have at least one email that is correctly formatted. 

Before pressing enter: 

![image](https://user-images.githubusercontent.com/61320526/134317609-aa772670-59c4-4399-b4fd-d70dbeee053f.png)

After pressing enter: 

![image](https://user-images.githubusercontent.com/61320526/134318049-ef064e72-ad2b-41c9-b792-9d669ab17dac.png)

**Comment by BeccaMelhuish** [comment]
Also the problem of not knowing how to actually add the email addresses is still an issue it seems.

As per my comments above (see June 16th) my feeling (and my own experience, until I got the habit after several times of getting it wrong) is that the user will click on the "Save topic" as there is no indication that they need to "press enter to add" and even if there was / when there is (when they enter correct format emails) it's not very instinctive when there is a big shiny button right there for them to click on instead.. 

@kevincrepin did you have some thoughts on this too? It's seems quite a big issue to me, but something which could be quite easily solved with an additional "Add users" button. Or in fact replacing the "Save topic" one, as I don't see that they would need to save any changes on this pop-up, it's only adding users in the Invite tab, or copying the URL in the Share one? But perhaps am missing something? 

![image](https://user-images.githubusercontent.com/61320526/134318757-5f97954d-2bda-4130-9abc-213c033cbfa8.png)

**Comment by BeccaMelhuish** [comment]
A further thing I spotted when testing this out - would it be possible for the red box to disappear once the email format is correct? Once I had added the .com to the email address the box is still red, but if I'm not mistaken (@kevincrepin will know for sure!) users are used to "flagged fields" like this turning "neutral" once the field is correctly filled? As if it remains red, they will feel as though they have still not correctly rectified the problem.. 

![image](https://user-images.githubusercontent.com/61320526/134320924-7eac7b21-d932-407a-82aa-c91a4b6a3d3c.png)

**Comment by anettlinno** [comment]
I see that there is an additional button on the invite users bar in current version "Press enter to add" and I believe that adding email addresses is not an issue any more, @BeccaMelhuish? 

![Add](https://user-images.githubusercontent.com/45175679/136923383-e7630819-8c98-4689-ae98-5523d96d3cf3.png)

I tested (both on the test environment and on our platform) inserting invalid email formats and incorrectly formatted email addresses silently disappears when I click "Press to add" or "Enter". Just to update the progress -- how far are we with this development @ilmartyrk (as the issue is in Done - live column and I read the explanation, why it´s there)? 

PS! I absolutely love the proposed solution: https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=180%3A17837

**Comment by anettlinno** [comment]
Triage 49. There are two issues left to solve:

1. When adding list of emails, then we are missing indication button "Press enter to add" that helps user to understand how to insert emails.
2. When user enters single invalid email address then our system doesn´t show the error message. 

Est. dev. time 2 hours. Sending to development.

**Comment by tiblu** [comment]
## TODO

- [x] Topic invites
  - [x] Expand the list of possible e-mail separators to `; <space>,`
  - [x] "Press enter to add" for the search box
  - [x] Make sure works:
      - [x] `asdasdas asdasd@asadas.com` - MUST show 1 in invalid list, 1 in OK list.
      - [x] `xasdasd@asadas.com xasdasdas` - MUST show 1 in invalid list, 1 in OK list.
      - [x] `xxasdasda` - MUST show 1 in invalid list
      - [x] `yyyasdasd@asdasd.com` - MUST show 1 in OK list.
      - [x] `peep@peep.com, teet@teet.com` - MUST show 2 in the OK list
  - [x] Show error for a single e-mail / string

**Comment by tiblu** [comment]
## RELEASE

![image](https://user-images.githubusercontent.com/7405383/142450393-35644738-e9eb-45c4-bebf-6fdcc773ffa3.png)

Topic invites ONLY. NO changes to Group invites as this needs more work.

Implementation notes:

* Now following are valid e-mail address separators - comma, whitespace, semicolon
* The "Press enter or click to add" hint appears ONLY when:
    * There is something entered in the search text box.
    * The search returned no results.
* Invalid e-mail list is now incremental - that is, every new search does not clear the existing list BUT updates it.

**Comment by tiblu** [comment]
@anettlinno @ilmartyrk To make a same UX for the Group invites, we MUST invest about 6-8hrs of work. 
Are we making a separate GH issue or I will do it in the scope of this one?

**Comment by anettlinno** [comment]
> @anettlinno @ilmartyrk To make a same UX for the Group invites, we MUST invest about 6-8hrs of work. Are we making a separate GH issue or I will do it in the scope of this one?

Tested and works beautifully with topic invites! :) 
Yes, we definitely should do the same UX for the Groups invites and I think we could do it under the same issue.

**Comment by tiblu** [comment]
## TODO - Group invites

- [ ] Group invites
  - [x] Add the invalid list of e-mails functionality that Topic invites have.
  - [x] Expand the list of possible e-mail separators to `; <space>,`
  - [x] "Press enter to add" for the search box
  - [x] Make sure works:
      - [x] `asdasdas asdasd@asadas.com` - MUST show 1 in invalid list, 1 in OK list.
      - [x] `xasdasd@asadas.com;xasdasdas` - MUST show 1 in invalid list, 1 in OK list.
      - [x] `xxasdasda` - MUST show 1 in invalid list
      - [x] `yyyasdasd@asdasd.com` - MUST show 1 in OK list.
      - [x] `peep@peep.com, teet@teet.com` - MUST show 2 in the OK list
      - [x] Correcting an invalid input to an existing email MUST NOT add duplicates.
      - [x] BUG: `addCorrectedEmail` deletes wrong line (always last/first)
  - [x] Show error for a single e-mail / string

**Comment by tiblu** [comment]
## RELEASE - Group invites

![image](https://user-images.githubusercontent.com/7405383/142647651-2a7b77c0-5efd-4dc5-a079-f4a18eb0f634.png)

Group invites UX has been synced with Topic invites.

Implementation notes:

* Now following are valid e-mail address separators - comma, whitespace, semicolon
* The "Press enter or click to add" hint appears ONLY when:
    * There is something entered in the search text box.
    * The search returned no results.
* Invalid e-mail list is now incremental - that is, every new search does not clear the existing list BUT updates it.

**Comment by anettlinno** [comment]
Tested. Works beautifully -- thanks a million, @tiblu! :)
