### ISSUE TITLE
TECH DEPT: Migrate Travis-CI.org builds to Travis-CI.com

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#737]
**Intro**

We are using Travis CI builds to verify integrity of our codebase for following projects:

* citizenos-fe

**TODO**

- [x] Create Citizen OS organization under Travis-CI.com.
- [x] Add ONLY projects that have `.travis.yml` in the project root to the build list. Grant Travis acess ONLY to these repositories.
     - [x] citizenos-fe
     - [x] etherpad-lite-heroku - NOTE: **Did not add**, as this runs EP tests, we MAY want to add it, but requires thinking if it adds any value and IF it does, needs verifying that the tests actually run.
- [x] Remove all from Travis-CI.org - that includes organizations, permissions - delete account.
