### ISSUE TITLE
Complete account registration flow

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#773]
When a user that doesn't have an account yet, gets invited to a topic or group, he/she gets an invite link to email. After clicking that link, user is redirected to our app and displayed a message that says "Log in with e-mail to access this topic" 
![invite](https://user-images.githubusercontent.com/19904307/133056861-7d9c085f-7576-42ae-91f1-65e3306d28f3.PNG)
after clicking that button, we display login form with e-mail pre-filled. 
![login](https://user-images.githubusercontent.com/19904307/133056905-5c0aa99f-33a9-44d2-a7a4-a7fe793a4261.PNG)
If user has not registered an account before, he/she then would likely click "No account? Sign up now" link instead of forgot password. And if he/she tries to register a new account then an error that e-mail is already in use is displayed. 

To keep all this from happening @kevincrepin, we need complete your account registering flow.

**Comment by kevincrepin** [comment]
@ilmartyrk do I understand correctly that if user gets invited then after pressing the "log in with email" button there would be a "complete your account" flow, because the account has already (kindof) been created? And it's because of that that this error gets displayed?

**Comment by ilmartyrk** [comment]
@kevincrepin that is correct. We create a new User in database to make the connections necessary for the app, but the person who has been invited by e-mail could possibly never have even been on our site. So I believe that displaying the login form could be quite confusing. We can possibly make it even clearer and for these new users we can replace the "log in with email" button with "complete your account"

**Comment by kevincrepin** [comment]
For some reason I hadn't linked this yet: https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=1089%3A29410

**Comment by anettlinno** [comment]
Triage 56. Needs some investigation on API side to be sure that it would be safe. Design looks good and solution is more understandable for new users. Approx. dev. time 1 day. Sending to development.

**Comment by tiblu** [comment]
### Initial testing

* Invited non-existing User (citizenos-gh-issue-773-test-user3)
* Opened e-mail link for that User (citizenos-gh-issue-773-test-user3)
* Tried to log in with the e-mail, no success. Error "We couldn’t find an account with that e-mail & password combination. Maybe you want to register a new account?" was shown.
* Started a registration process.
    * **NOTE:** e-mail address was not pre-filled on the registration form.  
* After registration User was successfully logged in, NO account already exists error.
* User WAS NOT redirected back to the invite.
* User had the invite pending in the Activity feed.
* Clicking the Activity feed item granted access to the Topic.

#### Conclusion

The flow IS NOT broken, but is not User friendly either.
Definitely needs improvement.

### TODO

- [x] API
    - [x] `/api/routes/auth.js` to use `asyncMiddleware` 
    - [x] `GET /api/users/:userId/topics/:topicId/invites/users/:inviteId` - return 20002 code for a existing non-registered User so that we would know in FE if we show login or signup flow.  (20001 was taken - user already has access)
        - [x] Is it safe to assume that if user `password IS NULL` is true, then the User has been invited? We need to check if signup with Google/FB/ESTEEID set a password or not. **NO, ITS NOT SAFE TO ASSUME** - FB/Google create accounts with email that have no password. The way to check is that password is null, the source is `citizenos` and there are NO `UserConnections`.
        - [x] DB migration - update comment on `Users.password` - `Password hash. NULL if User was created on invitation OR with another method like ESTEID, FB, Google.`
    - [x] `GET /api/groups/:groupId/invites/users/:inviteId` - return 20002 code for a existing non-registered User so that we would know in FE if we show login or signup flow.  (20001 was taken - user already has access)
- [x] FE
    - [x] Handle new   20002 code from `GET /api/users/:userId/topics/:topicId/invites/users/:inviteId` and initiate signup flow.
    - [x] Signup flow visuals:
        - [x] Topic invitation
        - [x] Group invitation 

### Testing

- [x] Topic invite flow
    - [x] Invite unregistered User:
         - [x] BUG: `name` set in registration flow was overwritten to the one parsed from the e-mail - problem caused by `POST /invites/users` creating a User (with name from e-mail), then signup complete process calls `POST /api/auth/signup` that ONLY updates `password` for User if there is one.
    - [x] Invite registered User 
- [x] Group invite flow
    - [x] Invite unregistered User
    - [x] Invite registered User

**Comment by tiblu** [comment]
## Released 03.02.2022

![image](https://user-images.githubusercontent.com/7405383/152367386-d25625f9-4fbf-4df9-ace3-d4cc8ba9de8c.png)


### Implementation notes:

* Flow is visible ONLY to Users who have NOT been registered, their User account has been created by the invite, not by the User.
* Flow is same for Topic and Group invites.
* When registering, at this moment User CAN change the pre-filled e-mail to whatever they like. We MAY:
     * want to provide User to a way to accept this invite with a different e-mail. FEELS like significant amount of work.
     * want to disable the field, force User to use the one in the invite. Easy to implement.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @anettlinno Was just looking at this for the Help Centre texts and wondering: Does this mean that anyone who is invited by email before having created an account is forced into creating an account with their email address rather than social login, and if so what does this mean for them if they want to use their social login (connected to the same email address) in future. 

For example, say I've never used COS and am invited to my Gmail email address, so I go ahead and create a COS account using that email address (email sign in, no social media). And then the next time I come to use COS I try to log in using my Gmail login, as it was the same email address as I was invited to. Does it take me into the same account (that I had first created with email), or create a new one somehow, or there's an error? And then a third time, say my Facebook is connected to my same gmail email address too (quite likely), what happens if I try logging in via Facebook - same questions :)

**Comment by BeccaMelhuish** [comment]
@ssin1901 tagging you in this one too just in case it's something you want to look into - see above :). 

(Related to the "creating an account" HC text which I'll add a link in the comments for to this now too).

**Comment by ssin1901** [comment]
@BeccaMelhuish very relevant! 

**Case 1**
So if the user chooses to not register via the email link but to create an account using the one step social login then they are able to access the topic invitation via their user dashboard.

<img width="818" alt="Systemscreenshot" src="https://user-images.githubusercontent.com/72747107/179398247-c04b8851-f94c-468c-bf1e-385f0e68bcf0.png">


**Case 2**
User uses the invitation link and therefore the email + password to create an account. In that case they are notified that a new login method has been added to their account and the account remains the same (with topic invitation).

<img width="1163" alt="NotificationLogin" src="https://user-images.githubusercontent.com/72747107/179398419-165fee77-c6ad-4b4c-9ef2-9bf4725fb641.png">

So while all is working well, I am wondering why users who receive an email invitation are kind of being forced to use the email + password option.

**Comment by BeccaMelhuish** [comment]
Thanks @ssin1901! So just to check I've understood correctly, are you saying that it is possible to add several different login methods to the same account, for example this scenario:

- The first time I ever log in to COS I use the email and password option with becca@gmail.com and the account gets created 
- The second time I log in I use the Gmail social login with becca@gmail.com a new login method gets added to the above account
- The third time I log in I use my Facebook (which also is connected to becca@gmail.com) a further new login method gets added to the above account

---> So by the end of these three separate logins I still just have one account but with three different ways of logging into it? 

And yeah I agree it seems odd that new invited users are being to some extent forced to log in with email and password, but maybe @ilmartyrk knows why? :)

**Comment by BeccaMelhuish** [comment]
@ssin1901 also interested in what you meant here: "then they are able to access the topic invitation via their user dashboard", as I didn't think it was possible to do this (but great news if it is!) - where can they do this?

**Comment by anettlinno** [comment]
> Thanks @ssin1901! So just to check I've understood correctly, are you saying that it is possible to add several different login methods to the same account, for example this scenario:
> 
> * The first time I ever log in to COS I use the email and password option with [becca@gmail.com](mailto:becca@gmail.com) and the account gets created
> * The second time I log in I use the Gmail social login with [becca@gmail.com](mailto:becca@gmail.com) a new login method gets added to the above account
> * The third time I log in I use my Facebook (which also is connected to [becca@gmail.com](mailto:becca@gmail.com)) a further new login method gets added to the above account
> 
> ---> So by the end of these three separate logins I still just have one account but with three different ways of logging into it?
> 

@BeccaMelhuish yes, our system recognizes users by their email (UserID is related to the email address). Even if you use separate logins as you just described above, you always land on the same user´s account. Tested it out.

**Comment by anettlinno** [comment]
> 
> So while all is working well, I am wondering why users who receive an email invitation are kind of being forced to use the email + password option.

Very much agree! I´ll open separate issue on that, then we can move this discussion there
